package eventsgen

import (
	"encoding/json"
	"sort"

	"github.com/mrs1lentcz/protobridge/internal/parser"
)

// generateAsyncAPI renders an AsyncAPI 3.0 document covering every event
// in the request. Output is JSON (AsyncAPI accepts both JSON and YAML;
// JSON is friendlier for downstream tooling and matches what we already
// do for openrpc.json). Schemas inline message field structures via the
// shared parser.MessageType graph.
//
// Channels are keyed by subject; the operation per channel is `send`
// because we describe the producer side of the contract. Subscriber
// codegen consumers can treat the same document as `receive` — AsyncAPI
// channel direction is a convention, not a runtime constraint.
func generateAsyncAPI(events []*parser.Event, messages map[string]*parser.MessageType) string {
	doc := asyncAPIDoc{
		AsyncAPI: "3.0.0",
		Info: asyncAPIInfo{
			Title:       "protobridge events",
			Version:     "0.0.0",
			Description: "Auto-generated by protoc-gen-events-go from proto annotations.",
		},
		Channels:   map[string]asyncAPIChannel{},
		Operations: map[string]asyncAPIOperation{},
		Components: asyncAPIComponents{Messages: map[string]asyncAPIMessage{}},
	}

	// Stable order — alphabetical by subject.
	sorted := append([]*parser.Event(nil), events...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Subject < sorted[j].Subject })

	for _, ev := range sorted {
		channelID := ev.Subject
		messageID := ev.Message.Name

		doc.Channels[channelID] = asyncAPIChannel{
			Address:     ev.Subject,
			Description: ev.Description,
			Messages: map[string]asyncAPIMessageRef{
				messageID: {Ref: "#/components/messages/" + messageID},
			},
		}

		// One operation per channel; action `send` describes the producer.
		// Consumers can reuse the same payload schema for their `receive`.
		doc.Operations["send_"+channelID] = asyncAPIOperation{
			Action:  "send",
			Channel: asyncAPIRef{Ref: "#/channels/" + channelID},
		}

		if _, exists := doc.Components.Messages[messageID]; !exists {
			doc.Components.Messages[messageID] = asyncAPIMessage{
				Name:        messageID,
				Title:       messageID,
				ContentType: "application/x-protobuf",
				Payload:     payloadSchema(ev.Message, messages),
			}
		}
	}

	out, _ := json.MarshalIndent(doc, "", "  ")
	return string(out)
}

func payloadSchema(mt *parser.MessageType, messages map[string]*parser.MessageType) map[string]any {
	if mt == nil {
		return map[string]any{"type": "object"}
	}
	return inlineMessageSchema(mt, messages, map[string]bool{})
}

// inlineMessageSchema produces a JSON-Schema-style payload description for an
// AsyncAPI message. It mirrors the mcpgen schema generator's shape (so
// downstream tools can consume both interchangeably) but lives here to keep
// internal/eventsgen self-contained — no cross-plugin dependency.
func inlineMessageSchema(mt *parser.MessageType, messages map[string]*parser.MessageType, seen map[string]bool) map[string]any {
	if seen[mt.FullName] {
		return map[string]any{"type": "object", "title": mt.Name}
	}
	seenCopy := make(map[string]bool, len(seen)+1)
	for k, v := range seen {
		seenCopy[k] = v
	}
	seenCopy[mt.FullName] = true

	props := map[string]any{}
	var required []string
	for _, f := range mt.Fields {
		props[f.Name] = inlineFieldSchema(f, messages, seenCopy)
		if f.Required {
			required = append(required, f.Name)
		}
	}
	out := map[string]any{
		"type":       "object",
		"properties": props,
	}
	if len(required) > 0 {
		out["required"] = required
	}
	return out
}

func inlineFieldSchema(f *parser.Field, messages map[string]*parser.MessageType, seen map[string]bool) map[string]any {
	switch {
	case f.Repeated:
		return map[string]any{"type": "array", "items": fieldKindSchema(f, messages, seen)}
	default:
		return fieldKindSchema(f, messages, seen)
	}
}

func fieldKindSchema(f *parser.Field, messages map[string]*parser.MessageType, seen map[string]bool) map[string]any {
	// Mirror mcpgen's scalar/enum mapping but keep this file self-contained.
	switch f.Type.String() {
	case "TYPE_STRING":
		return map[string]any{"type": "string"}
	case "TYPE_INT32", "TYPE_SINT32", "TYPE_SFIXED32":
		return map[string]any{"type": "integer", "format": "int32"}
	case "TYPE_INT64", "TYPE_SINT64", "TYPE_SFIXED64":
		return map[string]any{"type": "integer", "format": "int64"}
	case "TYPE_UINT32", "TYPE_FIXED32":
		return map[string]any{"type": "integer", "format": "uint32"}
	case "TYPE_UINT64", "TYPE_FIXED64":
		return map[string]any{"type": "integer", "format": "uint64"}
	case "TYPE_FLOAT":
		return map[string]any{"type": "number", "format": "float"}
	case "TYPE_DOUBLE":
		return map[string]any{"type": "number", "format": "double"}
	case "TYPE_BOOL":
		return map[string]any{"type": "boolean"}
	case "TYPE_BYTES":
		return map[string]any{"type": "string", "format": "byte"}
	case "TYPE_ENUM":
		out := map[string]any{"type": "string"}
		if len(f.EnumValues) > 0 {
			values := make([]string, 0, len(f.EnumValues))
			for _, ev := range f.EnumValues {
				name := ev.Name
				if ev.XVarName != "" {
					name = ev.XVarName
				}
				values = append(values, name)
			}
			out["enum"] = values
		}
		return out
	case "TYPE_MESSAGE":
		if nested, ok := messages[f.TypeName]; ok && nested != nil && len(nested.Fields) > 0 {
			return inlineMessageSchema(nested, messages, seen)
		}
		stub := map[string]any{"type": "object"}
		if i := lastSegment(f.TypeName); i != "" {
			stub["title"] = i
		}
		return stub
	default:
		return map[string]any{"type": "string"}
	}
}

func lastSegment(typeName string) string {
	for i := len(typeName) - 1; i >= 0; i-- {
		if typeName[i] == '.' {
			return typeName[i+1:]
		}
	}
	return typeName
}

// --- AsyncAPI document types ---

type asyncAPIDoc struct {
	AsyncAPI   string                       `json:"asyncapi"`
	Info       asyncAPIInfo                 `json:"info"`
	Channels   map[string]asyncAPIChannel   `json:"channels"`
	Operations map[string]asyncAPIOperation `json:"operations"`
	Components asyncAPIComponents           `json:"components"`
}

type asyncAPIInfo struct {
	Title       string `json:"title"`
	Version     string `json:"version"`
	Description string `json:"description,omitempty"`
}

type asyncAPIChannel struct {
	Address     string                        `json:"address"`
	Description string                        `json:"description,omitempty"`
	Messages    map[string]asyncAPIMessageRef `json:"messages"`
}

type asyncAPIMessageRef struct {
	Ref string `json:"$ref"`
}

type asyncAPIOperation struct {
	Action  string      `json:"action"`
	Channel asyncAPIRef `json:"channel"`
}

type asyncAPIRef struct {
	Ref string `json:"$ref"`
}

type asyncAPIComponents struct {
	Messages map[string]asyncAPIMessage `json:"messages"`
}

type asyncAPIMessage struct {
	Name        string         `json:"name"`
	Title       string         `json:"title,omitempty"`
	ContentType string         `json:"contentType,omitempty"`
	Payload     map[string]any `json:"payload"`
}
