// Package eventsgen is the codegen backend for the protoc-gen-events-go
// plugin. It emits typed Emit*/Subscribe* helpers (one .go file per Go
// package) plus an AsyncAPI 3.0 schema describing every (protobridge.event)
// annotated message in the request.
package eventsgen

import (
	"fmt"
	"sort"
	"text/template"

	"github.com/mrs1lentcz/protobridge/internal/generator"
	"github.com/mrs1lentcz/protobridge/internal/parser"
)

// generateServiceBroadcastFile renders the broadcast WS handler for one
// (protobridge.broadcast) service. The output is a single .go file under the
// events output package containing:
//
//   - <Svc>BroadcastSubjects — every subject listed in the envelope oneof.
//   - <Svc>BroadcastEnvelope — per-subject proto → protojson marshaler that
//     produces the runtime JSON envelope wire shape.
//   - New<Svc>BroadcastHandler — one-call wireup returning an http.Handler
//     that the REST plugin mounts at the service's declared route.
//
// When the envelope references event messages from multiple Go packages the
// imports are aliased pb0, pb1, … (deterministic, collision-free). For the
// common single-package case the alias is the plain `pb`.
func generateServiceBroadcastFile(svc *parser.BroadcastService, outputPkg string) string {
	// Collect unique event GoPackages in declaration order so aliases stay
	// stable across runs (events are already sorted by declaration in parser).
	seen := map[string]int{}
	var pkgs []string
	for _, ev := range svc.Events {
		pkg := ev.GoPackage
		if pkg == "" {
			pkg = svc.GoPackage // fallback: assume same pkg as the service
		}
		if _, ok := seen[pkg]; !ok {
			seen[pkg] = len(pkgs)
			pkgs = append(pkgs, pkg)
		}
	}
	imports := make([]broadcastImport, len(pkgs))
	for i, p := range pkgs {
		alias := "pb"
		if len(pkgs) > 1 {
			alias = fmt.Sprintf("pb%d", i)
		}
		imports[i] = broadcastImport{Alias: alias, Path: p}
	}

	tmplEvents := make([]tmplBroadcastServiceEvent, 0, len(svc.Events))
	for _, ev := range svc.Events {
		pkg := ev.GoPackage
		if pkg == "" {
			pkg = svc.GoPackage
		}
		tmplEvents = append(tmplEvents, tmplBroadcastServiceEvent{
			MessageName: ev.Message.Name,
			Subject:     ev.Subject,
			Alias:       imports[seen[pkg]].Alias,
		})
	}

	data := broadcastServiceFileData{
		PkgName:     outputPkg,
		ServiceName: svc.Name,
		Route:       svc.Route,
		Imports:     imports,
		Events:      tmplEvents,
	}
	return generator.RenderTemplate(broadcastServiceTmpl, data)
}

type broadcastImport struct {
	Alias string
	Path  string
}

type broadcastServiceFileData struct {
	PkgName     string
	ServiceName string
	Route       string
	Imports     []broadcastImport
	Events      []tmplBroadcastServiceEvent
}

type tmplBroadcastServiceEvent struct {
	MessageName string
	Subject     string
	Alias       string // which imported package the message lives in
}

var broadcastServiceTmpl = template.Must(template.New("broadcast_service").Parse(`// Code generated by protoc-gen-events-go. DO NOT EDIT.

package {{ .PkgName }}

import (
	"encoding/json"
	"fmt"
	"net/http"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	"github.com/mrs1lentcz/protobridge/runtime/events"
{{ range .Imports }}	{{ .Alias }} {{ printf "%q" .Path }}
{{ end }})

// {{ .ServiceName }}Route is the HTTP path declared on the
// (protobridge.broadcast) service. Exported so custom routers can mount
// the handler without duplicating the literal.
const {{ .ServiceName }}Route = {{ printf "%q" .Route }}

// {{ .ServiceName }}Subjects lists every subject that appears in
// the envelope oneof, in proto declaration order.
var {{ .ServiceName }}Subjects = []string{
{{- range .Events }}
	{{ printf "%q" .Subject }},
{{- end }}
}

// {{ .ServiceName }}Envelope decodes a bus message for any of the
// subjects above and returns the JSON envelope emitted to WS clients.
func {{ .ServiceName }}Envelope(subject string, payload []byte, headers map[string]string) ([]byte, error) {
	jsonOpts := protojson.MarshalOptions{UseProtoNames: true}
	var msg proto.Message
	switch subject {
{{- range .Events }}
	case {{ printf "%q" .Subject }}:
		msg = &{{ .Alias }}.{{ .MessageName }}{}
{{- end }}
	default:
		return nil, fmt.Errorf("unknown broadcast subject %q", subject)
	}
	if err := proto.Unmarshal(payload, msg); err != nil {
		return nil, fmt.Errorf("decode %s: %w", subject, err)
	}
	encoded, err := jsonOpts.Marshal(msg)
	if err != nil {
		return nil, fmt.Errorf("encode %s: %w", subject, err)
	}
	return events.MarshalJSONEnvelope(subject, json.RawMessage(encoded), events.HeadersToLabels(headers))
}

// New{{ .ServiceName }}Handler returns the WebSocket handler for
// the (protobridge.broadcast) service. Bus, Subjects and Marshal are
// injected automatically; cfg carries PrincipalLabels, Matcher,
// OriginPatterns and Logger from the caller.
func New{{ .ServiceName }}Handler(bus events.Bus, cfg events.BroadcastConfig) http.Handler {
	cfg.Bus = bus
	cfg.Subjects = {{ .ServiceName }}Subjects
	cfg.Marshal = {{ .ServiceName }}Envelope
	return events.NewBroadcastHandler(cfg)
}
`))

// generateEventsFile renders one Go file per Go package containing every
// event from that package. Grouping by package keeps the output flat and
// matches the convention `protoc-gen-go` uses (one .pb.go per .proto file)
// — but events are message-level annotations that may live anywhere in the
// proto graph, so we group by the resolved Go import path instead.
func generateEventsFile(pkgPath, outputPkg string, events []*parser.Event) string {
	if len(events) == 0 {
		// Caller (Generate) only ever passes a non-empty slice — defensive
		// panic surfaces a regression instead of silently emitting nothing.
		panic("eventsgen: no events for package " + pkgPath)
	}

	// Stable order: alphabetical by message name. Generated files diff only
	// when the proto changes.
	sort.Slice(events, func(i, j int) bool {
		return events[i].Message.Name < events[j].Message.Name
	})

	data := fileData{
		ProtoImport: pkgPath,
		PkgName:     outputPkg,
	}
	for _, ev := range events {
		td := tmplEvent{
			MessageName:  ev.Message.Name,
			Subject:      ev.Subject,
			DurableGroup: ev.DurableGroup,
			Description:  ev.Description,
			KindBroadcast: ev.Kind == parser.EventKindBroadcast,
			KindDurable:   ev.Kind == parser.EventKindDurable,
			KindBoth:      ev.Kind == parser.EventKindBoth,
		}
		data.Events = append(data.Events, td)
	}

	return generator.RenderTemplate(eventsTmpl, data)
}

type fileData struct {
	ProtoImport string
	PkgName     string
	Events      []tmplEvent
}

type tmplEvent struct {
	MessageName   string
	Subject       string
	DurableGroup  string
	Description   string
	KindBroadcast bool
	KindDurable   bool
	KindBoth      bool
}

var eventsTmpl = template.Must(template.New("events").Parse(`// Code generated by protoc-gen-events-go. DO NOT EDIT.

package {{ .PkgName }}

import (
	"context"
	"fmt"

	"google.golang.org/protobuf/proto"

	"github.com/mrs1lentcz/protobridge/runtime/events"
	pb "{{ .ProtoImport }}"
)

{{ range .Events }}

// Subject{{ .MessageName }} is the bus subject this event is published on.
const Subject{{ .MessageName }} = {{ printf "%q" .Subject }}

// Emit{{ .MessageName }} marshals ev and publishes it on the bus using the
// kind declared in the proto annotation. Labels stashed on ctx via
// events.WithLabels are forwarded as message headers so subscribers
// (and the broadcast WS endpoint) can route on them.{{ if .Description }}
//
// {{ .Description }}{{ end }}
func Emit{{ .MessageName }}(ctx context.Context, bus events.Bus, ev *pb.{{ .MessageName }}) error {
	if ev == nil {
		return fmt.Errorf("Emit{{ .MessageName }}: nil event")
	}
	payload, err := proto.Marshal(ev)
	if err != nil {
		return fmt.Errorf("Emit{{ .MessageName }}: marshal: %w", err)
	}
	headers := events.LabelsToHeaders(events.LabelsFromContext(ctx), nil)
	return bus.Publish(ctx, Subject{{ .MessageName }}, payload, {{ if .KindBroadcast }}events.KindBroadcast{{ else if .KindDurable }}events.KindDurable{{ else if .KindBoth }}events.KindBoth{{ else }}events.KindUnspecified{{ end }}, headers)
}

// {{ .MessageName }}Handler is the typed signature for {{ .MessageName }}
// subscribers — declared once and reused by both Subscribe{{ .MessageName }}
// (durable) and SubscribeBroadcast{{ .MessageName }} (fan-out) so callers
// can swap between transports without changing the handler type.
type {{ .MessageName }}Handler func(ctx context.Context, ev *pb.{{ .MessageName }}) error

{{ if or .KindDurable .KindBoth }}
// Subscribe{{ .MessageName }} registers a load-balanced at-least-once
// subscriber. group identifies the consumer group; multiple processes in
// the same group split the message stream. Pass an empty string to use
// {{ if .DurableGroup }}{{ printf "%q" .DurableGroup }} (declared in the proto annotation){{ else }}the message name as the default group identifier{{ end }}.
func Subscribe{{ .MessageName }}(bus events.Bus, group string, h {{ .MessageName }}Handler) (events.Subscription, error) {
	if group == "" {
		group = {{ if .DurableGroup }}{{ printf "%q" .DurableGroup }}{{ else }}Subject{{ .MessageName }}{{ end }}
	}
	return bus.SubscribeDurable(Subject{{ .MessageName }}, group, func(ctx context.Context, m events.Message) error {
		ev := &pb.{{ .MessageName }}{}
		if err := proto.Unmarshal(m.Payload, ev); err != nil {
			m.Nack()
			return fmt.Errorf("Subscribe{{ .MessageName }}: unmarshal: %w", err)
		}
		if err := h(ctx, ev); err != nil {
			m.Nack()
			return err
		}
		m.Ack()
		return nil
	})
}
{{ end }}

{{ if or .KindBroadcast .KindBoth }}
// SubscribeBroadcast{{ .MessageName }} registers an ephemeral fan-out
// subscriber. Every subscriber sees every message; missed messages while
// disconnected are not redelivered.
func SubscribeBroadcast{{ .MessageName }}(bus events.Bus, h {{ .MessageName }}Handler) (events.Subscription, error) {
	return bus.SubscribeBroadcast(Subject{{ .MessageName }}, func(ctx context.Context, m events.Message) error {
		ev := &pb.{{ .MessageName }}{}
		if err := proto.Unmarshal(m.Payload, ev); err != nil {
			return fmt.Errorf("SubscribeBroadcast{{ .MessageName }}: unmarshal: %w", err)
		}
		return h(ctx, ev)
	})
}
{{ end }}

{{ end }}
`))

