// Package eventsgen is the codegen backend for the protoc-gen-events-go
// plugin. It emits typed Emit*/Subscribe* helpers (one .go file per Go
// package) plus an AsyncAPI 3.0 schema describing every (protobridge.event)
// annotated message in the request.
package eventsgen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"text/template"

	"github.com/mrs1lentcz/protobridge/internal/parser"
)

// generateEventsFile renders one Go file per Go package containing every
// event from that package. Grouping by package keeps the output flat and
// matches the convention `protoc-gen-go` uses (one .pb.go per .proto file)
// — but events are message-level annotations that may live anywhere in the
// proto graph, so we group by the resolved Go import path instead.
func generateEventsFile(pkgPath string, events []*parser.Event) (string, error) {
	if len(events) == 0 {
		return "", fmt.Errorf("eventsgen: no events for package %q", pkgPath)
	}

	// Stable order: alphabetical by message name. Generated files diff only
	// when the proto changes.
	sort.Slice(events, func(i, j int) bool {
		return events[i].Message.Name < events[j].Message.Name
	})

	data := fileData{
		ProtoImport: pkgPath,
		PkgName:     "events", // generated package — see plugin entry for path resolution
	}
	for _, ev := range events {
		td := tmplEvent{
			MessageName:  ev.Message.Name,
			Subject:      ev.Subject,
			DurableGroup: ev.DurableGroup,
			Description:  ev.Description,
			KindBroadcast: ev.Kind == parser.EventKindBroadcast,
			KindDurable:   ev.Kind == parser.EventKindDurable,
			KindBoth:      ev.Kind == parser.EventKindBoth,
		}
		data.Events = append(data.Events, td)
	}

	var buf bytes.Buffer
	if err := eventsTmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("gofmt events file: %w\n%s", err, buf.String())
	}
	return string(formatted), nil
}

type fileData struct {
	ProtoImport string
	PkgName     string
	Events      []tmplEvent
}

type tmplEvent struct {
	MessageName   string
	Subject       string
	DurableGroup  string
	Description   string
	KindBroadcast bool
	KindDurable   bool
	KindBoth      bool
}

var eventsTmpl = template.Must(template.New("events").Parse(`// Code generated by protoc-gen-events-go. DO NOT EDIT.

package {{ .PkgName }}

import (
	"context"
	"fmt"

	"google.golang.org/protobuf/proto"

	"github.com/mrs1lentcz/protobridge/runtime/events"
	pb "{{ .ProtoImport }}"
)

{{ range .Events }}

// Subject{{ .MessageName }} is the bus subject this event is published on.
const Subject{{ .MessageName }} = {{ printf "%q" .Subject }}

// Emit{{ .MessageName }} marshals ev and publishes it on the bus using the
// kind declared in the proto annotation.{{ if .Description }}
//
// {{ .Description }}{{ end }}
func Emit{{ .MessageName }}(ctx context.Context, bus events.Bus, ev *pb.{{ .MessageName }}) error {
	if ev == nil {
		return fmt.Errorf("Emit{{ .MessageName }}: nil event")
	}
	payload, err := proto.Marshal(ev)
	if err != nil {
		return fmt.Errorf("Emit{{ .MessageName }}: marshal: %w", err)
	}
	return bus.Publish(ctx, Subject{{ .MessageName }}, payload, {{ if .KindBroadcast }}events.KindBroadcast{{ else if .KindDurable }}events.KindDurable{{ else if .KindBoth }}events.KindBoth{{ else }}events.KindUnspecified{{ end }}, nil)
}

{{ if or .KindDurable .KindBoth }}
// {{ .MessageName }}Handler is the typed signature for {{ .MessageName }} subscribers.
type {{ .MessageName }}Handler func(ctx context.Context, ev *pb.{{ .MessageName }}) error

// Subscribe{{ .MessageName }} registers a load-balanced at-least-once
// subscriber. group identifies the consumer group; multiple processes in
// the same group split the message stream. Pass an empty string to use
// {{ if .DurableGroup }}{{ printf "%q" .DurableGroup }} (declared in the proto annotation){{ else }}the message name as the default group identifier{{ end }}.
func Subscribe{{ .MessageName }}(bus events.Bus, group string, h {{ .MessageName }}Handler) (events.Subscription, error) {
	if group == "" {
		group = {{ if .DurableGroup }}{{ printf "%q" .DurableGroup }}{{ else }}Subject{{ .MessageName }}{{ end }}
	}
	return bus.SubscribeDurable(Subject{{ .MessageName }}, group, func(ctx context.Context, m events.Message) error {
		ev := &pb.{{ .MessageName }}{}
		if err := proto.Unmarshal(m.Payload, ev); err != nil {
			m.Nack()
			return fmt.Errorf("Subscribe{{ .MessageName }}: unmarshal: %w", err)
		}
		if err := h(ctx, ev); err != nil {
			m.Nack()
			return err
		}
		m.Ack()
		return nil
	})
}
{{ end }}

{{ if or .KindBroadcast .KindBoth }}
// SubscribeBroadcast{{ .MessageName }} registers an ephemeral fan-out
// subscriber. Every subscriber sees every message; missed messages while
// disconnected are not redelivered.
func SubscribeBroadcast{{ .MessageName }}(bus events.Bus, h {{ .MessageName }}Handler) (events.Subscription, error) {
	return bus.SubscribeBroadcast(Subject{{ .MessageName }}, func(ctx context.Context, m events.Message) error {
		ev := &pb.{{ .MessageName }}{}
		if err := proto.Unmarshal(m.Payload, ev); err != nil {
			return fmt.Errorf("SubscribeBroadcast{{ .MessageName }}: unmarshal: %w", err)
		}
		return h(ctx, ev)
	})
}
{{ end }}

{{ end }}
`))

