// Package eventsgen is the codegen backend for the protoc-gen-events-go
// plugin. It emits typed Emit*/Subscribe* helpers (one .go file per Go
// package) plus an AsyncAPI 3.0 schema describing every (protobridge.event)
// annotated message in the request.
package eventsgen

import (
	"sort"
	"strings"
	"text/template"

	"github.com/mrs1lentcz/protobridge/internal/generator"
	"github.com/mrs1lentcz/protobridge/internal/parser"
)

// generateBroadcastFile renders the broadcast WS handler for one Go
// package: a typed envelope marshaler that knows every PUBLIC broadcast
// subject in the package, plus a Register helper that mounts the runtime
// broadcast handler on a chi router. Returns "" when the package has no
// events with PUBLIC visibility (consumer skips emitting the file).
func generateBroadcastFile(pkgPath, outputPkg string, events []*parser.Event) string {
	var public []tmplBroadcastEvent
	for _, ev := range events {
		// Broadcast WS only carries fan-out events. Pure DURABLE events are
		// internal work-queue traffic and don't belong on a public stream.
		isFanOut := ev.Kind == parser.EventKindBroadcast || ev.Kind == parser.EventKindBoth
		if !isFanOut {
			continue
		}
		if ev.Visibility != parser.EventVisibilityPublic {
			continue
		}
		public = append(public, tmplBroadcastEvent{
			MessageName: ev.Message.Name,
			Subject:     ev.Subject,
		})
	}
	if len(public) == 0 {
		return ""
	}
	sort.Slice(public, func(i, j int) bool { return public[i].MessageName < public[j].MessageName })

	pkgLeaf := pkgPath
	if i := strings.LastIndex(pkgPath, "/"); i >= 0 {
		pkgLeaf = pkgPath[i+1:]
	}

	data := broadcastFileData{
		ProtoImport: pkgPath,
		PkgName:     outputPkg,
		// Title-case the leaf so the generated symbols are exported Go
		// identifiers (e.g. "myapp" → "Myapp", "v1" → "V1"). Underscores
		// are preserved; we don't try to be too clever here.
		PackageID: titleCaseLeaf(pkgLeaf),
		Events:    public,
	}
	return generator.RenderTemplate(broadcastTmpl, data)
}

// titleCaseLeaf upper-cases the first rune so symbols derived from a Go
// package leaf (e.g. "myapp", "v1") become exported Go identifiers
// ("Myapp", "V1"). It does not alter the rest of the string — generated
// symbols stay unambiguous between, say, "Myapp" and "MyApp".
func titleCaseLeaf(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'a' && r[0] <= 'z' {
		r[0] -= 32
	}
	return string(r)
}

type broadcastFileData struct {
	ProtoImport string
	PkgName     string
	PackageID   string
	Events      []tmplBroadcastEvent
}

type tmplBroadcastEvent struct {
	MessageName string
	Subject     string
}

var broadcastTmpl = template.Must(template.New("broadcast").Parse(`// Code generated by protoc-gen-events-go. DO NOT EDIT.

package {{ .PkgName }}

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	"github.com/mrs1lentcz/protobridge/runtime/events"
	pb "{{ .ProtoImport }}"
)

// {{ .PackageID }}BroadcastSubjects lists every PUBLIC broadcast subject
// in this package. Use it when wiring a custom router or composing with
// other broadcast groups.
var {{ .PackageID }}BroadcastSubjects = []string{
{{- range .Events }}
	{{ printf "%q" .Subject }},
{{- end }}
}

// {{ .PackageID }}BroadcastEnvelope is the per-package envelope marshaler.
// It unmarshals each subject's payload into the matching proto type and
// re-encodes it as protojson under the subject key, so WS clients see
// strongly-typed events regardless of the bus wire format.
func {{ .PackageID }}BroadcastEnvelope(subject string, payload []byte, _ map[string]string) ([]byte, error) {
	jsonOpts := protojson.MarshalOptions{UseProtoNames: true}
	var (
		msg proto.Message
	)
	switch subject {
{{- range .Events }}
	case {{ printf "%q" .Subject }}:
		msg = &pb.{{ .MessageName }}{}
{{- end }}
	default:
		return nil, fmt.Errorf("unknown broadcast subject %q", subject)
	}
	if err := proto.Unmarshal(payload, msg); err != nil {
		return nil, fmt.Errorf("decode %s: %w", subject, err)
	}
	encoded, err := jsonOpts.Marshal(msg)
	if err != nil {
		return nil, fmt.Errorf("encode %s: %w", subject, err)
	}
	return events.MarshalJSONEnvelope(subject, json.RawMessage(encoded))
}

// Register{{ .PackageID }}Broadcast mounts a WebSocket broadcast endpoint
// at "<prefix>" that streams every PUBLIC event in this package as a JSON
// envelope ({"subject": "...", "event": {...}}). prefix is typically
// something like "/events/{{ .PackageID }}".
//
// Auth, rate limiting, tenant filtering: compose with chi middleware on
// the router. The handler itself is auth-agnostic.
func Register{{ .PackageID }}Broadcast(r chi.Router, bus events.Bus, prefix string) {
	r.Method(http.MethodGet, prefix, events.NewBroadcastHandler(events.BroadcastConfig{
		Bus:      bus,
		Subjects: {{ .PackageID }}BroadcastSubjects,
		Marshal:  {{ .PackageID }}BroadcastEnvelope,
	}))
}
`))

// generateEventsFile renders one Go file per Go package containing every
// event from that package. Grouping by package keeps the output flat and
// matches the convention `protoc-gen-go` uses (one .pb.go per .proto file)
// — but events are message-level annotations that may live anywhere in the
// proto graph, so we group by the resolved Go import path instead.
func generateEventsFile(pkgPath, outputPkg string, events []*parser.Event) string {
	if len(events) == 0 {
		// Caller (Generate) only ever passes a non-empty slice — defensive
		// panic surfaces a regression instead of silently emitting nothing.
		panic("eventsgen: no events for package " + pkgPath)
	}

	// Stable order: alphabetical by message name. Generated files diff only
	// when the proto changes.
	sort.Slice(events, func(i, j int) bool {
		return events[i].Message.Name < events[j].Message.Name
	})

	data := fileData{
		ProtoImport: pkgPath,
		PkgName:     outputPkg,
	}
	for _, ev := range events {
		td := tmplEvent{
			MessageName:  ev.Message.Name,
			Subject:      ev.Subject,
			DurableGroup: ev.DurableGroup,
			Description:  ev.Description,
			KindBroadcast: ev.Kind == parser.EventKindBroadcast,
			KindDurable:   ev.Kind == parser.EventKindDurable,
			KindBoth:      ev.Kind == parser.EventKindBoth,
		}
		data.Events = append(data.Events, td)
	}

	return generator.RenderTemplate(eventsTmpl, data)
}

type fileData struct {
	ProtoImport string
	PkgName     string
	Events      []tmplEvent
}

type tmplEvent struct {
	MessageName   string
	Subject       string
	DurableGroup  string
	Description   string
	KindBroadcast bool
	KindDurable   bool
	KindBoth      bool
}

var eventsTmpl = template.Must(template.New("events").Parse(`// Code generated by protoc-gen-events-go. DO NOT EDIT.

package {{ .PkgName }}

import (
	"context"
	"fmt"

	"google.golang.org/protobuf/proto"

	"github.com/mrs1lentcz/protobridge/runtime/events"
	pb "{{ .ProtoImport }}"
)

{{ range .Events }}

// Subject{{ .MessageName }} is the bus subject this event is published on.
const Subject{{ .MessageName }} = {{ printf "%q" .Subject }}

// Emit{{ .MessageName }} marshals ev and publishes it on the bus using the
// kind declared in the proto annotation.{{ if .Description }}
//
// {{ .Description }}{{ end }}
func Emit{{ .MessageName }}(ctx context.Context, bus events.Bus, ev *pb.{{ .MessageName }}) error {
	if ev == nil {
		return fmt.Errorf("Emit{{ .MessageName }}: nil event")
	}
	payload, err := proto.Marshal(ev)
	if err != nil {
		return fmt.Errorf("Emit{{ .MessageName }}: marshal: %w", err)
	}
	return bus.Publish(ctx, Subject{{ .MessageName }}, payload, {{ if .KindBroadcast }}events.KindBroadcast{{ else if .KindDurable }}events.KindDurable{{ else if .KindBoth }}events.KindBoth{{ else }}events.KindUnspecified{{ end }}, nil)
}

// {{ .MessageName }}Handler is the typed signature for {{ .MessageName }}
// subscribers — declared once and reused by both Subscribe{{ .MessageName }}
// (durable) and SubscribeBroadcast{{ .MessageName }} (fan-out) so callers
// can swap between transports without changing the handler type.
type {{ .MessageName }}Handler func(ctx context.Context, ev *pb.{{ .MessageName }}) error

{{ if or .KindDurable .KindBoth }}
// Subscribe{{ .MessageName }} registers a load-balanced at-least-once
// subscriber. group identifies the consumer group; multiple processes in
// the same group split the message stream. Pass an empty string to use
// {{ if .DurableGroup }}{{ printf "%q" .DurableGroup }} (declared in the proto annotation){{ else }}the message name as the default group identifier{{ end }}.
func Subscribe{{ .MessageName }}(bus events.Bus, group string, h {{ .MessageName }}Handler) (events.Subscription, error) {
	if group == "" {
		group = {{ if .DurableGroup }}{{ printf "%q" .DurableGroup }}{{ else }}Subject{{ .MessageName }}{{ end }}
	}
	return bus.SubscribeDurable(Subject{{ .MessageName }}, group, func(ctx context.Context, m events.Message) error {
		ev := &pb.{{ .MessageName }}{}
		if err := proto.Unmarshal(m.Payload, ev); err != nil {
			m.Nack()
			return fmt.Errorf("Subscribe{{ .MessageName }}: unmarshal: %w", err)
		}
		if err := h(ctx, ev); err != nil {
			m.Nack()
			return err
		}
		m.Ack()
		return nil
	})
}
{{ end }}

{{ if or .KindBroadcast .KindBoth }}
// SubscribeBroadcast{{ .MessageName }} registers an ephemeral fan-out
// subscriber. Every subscriber sees every message; missed messages while
// disconnected are not redelivered.
func SubscribeBroadcast{{ .MessageName }}(bus events.Bus, h {{ .MessageName }}Handler) (events.Subscription, error) {
	return bus.SubscribeBroadcast(Subject{{ .MessageName }}, func(ctx context.Context, m events.Message) error {
		ev := &pb.{{ .MessageName }}{}
		if err := proto.Unmarshal(m.Payload, ev); err != nil {
			return fmt.Errorf("SubscribeBroadcast{{ .MessageName }}: unmarshal: %w", err)
		}
		return h(ctx, ev)
	})
}
{{ end }}

{{ end }}
`))

