// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protobridge/events.proto

package protobridge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED EventKind = 0
	// Fire-and-forget fan-out. Subscribers that are offline miss messages;
	// no replay. Backed by core NATS / Redis Pub/Sub / RabbitMQ fanout.
	EventKind_BROADCAST EventKind = 1
	// Persistent at-least-once delivery with consumer groups. Failed
	// handlers cause redelivery (backend-specific retry policy). Backed by
	// NATS JetStream / Redis Streams / RabbitMQ durable queues.
	EventKind_DURABLE EventKind = 2
	// Both paths in sequence: durable first (must succeed; error fails the
	// publish), then broadcast (best-effort; failure is logged and ignored).
	// Subscribers must be idempotent — they may see the same event from
	// both paths.
	EventKind_BOTH EventKind = 3
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "BROADCAST",
		2: "DURABLE",
		3: "BOTH",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED": 0,
		"BROADCAST":              1,
		"DURABLE":                2,
		"BOTH":                   3,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_protobridge_events_proto_enumTypes[0].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_protobridge_events_proto_enumTypes[0]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_protobridge_events_proto_rawDescGZIP(), []int{0}
}

type Visibility int32

const (
	Visibility_VISIBILITY_UNSPECIFIED Visibility = 0
	// Default. Event reaches the gateway broadcast service and is exposed
	// to external WS/SSE subscribers.
	Visibility_PUBLIC Visibility = 1
	// Event flows only to in-process / in-cluster gRPC subscribers. The
	// generated broadcast service omits these from its oneof envelope.
	Visibility_INTERNAL Visibility = 2
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "PUBLIC",
		2: "INTERNAL",
	}
	Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"PUBLIC":                 1,
		"INTERNAL":               2,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_protobridge_events_proto_enumTypes[1].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_protobridge_events_proto_enumTypes[1]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_protobridge_events_proto_rawDescGZIP(), []int{1}
}

type BroadcastOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP path where the WS endpoint is mounted. Must start with "/".
	Route         string `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastOptions) Reset() {
	*x = BroadcastOptions{}
	mi := &file_protobridge_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastOptions) ProtoMessage() {}

func (x *BroadcastOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protobridge_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastOptions.ProtoReflect.Descriptor instead.
func (*BroadcastOptions) Descriptor() ([]byte, []int) {
	return file_protobridge_events_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastOptions) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

type EventOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject / topic / routing key on the bus. Empty → derived from the
	// message name in snake_case (e.g. OrderCreated → order_created).
	// Exact-match only; wildcards are not supported.
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// How the bus should route this event.
	Kind EventKind `protobuf:"varint,2,opt,name=kind,proto3,enum=protobridge.EventKind" json:"kind,omitempty"`
	// For DURABLE / BOTH only: name of the consumer group for at-least-once
	// delivery. Multiple subscribers in the same group load-balance the stream.
	// Empty → derived from the subscriber's identity at registration.
	DurableGroup string `protobuf:"bytes,3,opt,name=durable_group,json=durableGroup,proto3" json:"durable_group,omitempty"`
	// For BROADCAST / BOTH only: visibility filter for the gateway broadcast
	// service. PUBLIC events flow to browser clients via WS/SSE; INTERNAL
	// events are visible only to in-cluster gRPC subscribers.
	Visibility Visibility `protobuf:"varint,4,opt,name=visibility,proto3,enum=protobridge.Visibility" json:"visibility,omitempty"`
	// Optional human-readable description, used in generated AsyncAPI docs.
	Description   string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventOptions) Reset() {
	*x = EventOptions{}
	mi := &file_protobridge_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventOptions) ProtoMessage() {}

func (x *EventOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protobridge_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventOptions.ProtoReflect.Descriptor instead.
func (*EventOptions) Descriptor() ([]byte, []int) {
	return file_protobridge_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventOptions) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EventOptions) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *EventOptions) GetDurableGroup() string {
	if x != nil {
		return x.DurableGroup
	}
	return ""
}

func (x *EventOptions) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

func (x *EventOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var file_protobridge_events_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*EventOptions)(nil),
		Field:         51234,
		Name:          "protobridge.event",
		Tag:           "bytes,51234,opt,name=event",
		Filename:      "protobridge/events.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*BroadcastOptions)(nil),
		Field:         51235,
		Name:          "protobridge.broadcast",
		Tag:           "bytes,51235,opt,name=broadcast",
		Filename:      "protobridge/events.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional protobridge.EventOptions event = 51234;
	E_Event = &file_protobridge_events_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional protobridge.BroadcastOptions broadcast = 51235;
	E_Broadcast = &file_protobridge_events_proto_extTypes[1]
)

var File_protobridge_events_proto protoreflect.FileDescriptor

const file_protobridge_events_proto_rawDesc = "" +
	"\n" +
	"\x18protobridge/events.proto\x12\vprotobridge\x1a google/protobuf/descriptor.proto\"(\n" +
	"\x10BroadcastOptions\x12\x14\n" +
	"\x05route\x18\x01 \x01(\tR\x05route\"\xd4\x01\n" +
	"\fEventOptions\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12*\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x16.protobridge.EventKindR\x04kind\x12#\n" +
	"\rdurable_group\x18\x03 \x01(\tR\fdurableGroup\x127\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2\x17.protobridge.VisibilityR\n" +
	"visibility\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription*M\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tBROADCAST\x10\x01\x12\v\n" +
	"\aDURABLE\x10\x02\x12\b\n" +
	"\x04BOTH\x10\x03*B\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x01\x12\f\n" +
	"\bINTERNAL\x10\x02:R\n" +
	"\x05event\x12\x1f.google.protobuf.MessageOptions\x18\xa2\x90\x03 \x01(\v2\x19.protobridge.EventOptionsR\x05event:^\n" +
	"\tbroadcast\x12\x1f.google.protobuf.ServiceOptions\x18\xa3\x90\x03 \x01(\v2\x1d.protobridge.BroadcastOptionsR\tbroadcastB5Z3github.com/mrs1lentcz/protobridge/proto/protobridgeb\x06proto3"

var (
	file_protobridge_events_proto_rawDescOnce sync.Once
	file_protobridge_events_proto_rawDescData []byte
)

func file_protobridge_events_proto_rawDescGZIP() []byte {
	file_protobridge_events_proto_rawDescOnce.Do(func() {
		file_protobridge_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobridge_events_proto_rawDesc), len(file_protobridge_events_proto_rawDesc)))
	})
	return file_protobridge_events_proto_rawDescData
}

var file_protobridge_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobridge_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobridge_events_proto_goTypes = []any{
	(EventKind)(0),                      // 0: protobridge.EventKind
	(Visibility)(0),                     // 1: protobridge.Visibility
	(*BroadcastOptions)(nil),            // 2: protobridge.BroadcastOptions
	(*EventOptions)(nil),                // 3: protobridge.EventOptions
	(*descriptorpb.MessageOptions)(nil), // 4: google.protobuf.MessageOptions
	(*descriptorpb.ServiceOptions)(nil), // 5: google.protobuf.ServiceOptions
}
var file_protobridge_events_proto_depIdxs = []int32{
	0, // 0: protobridge.EventOptions.kind:type_name -> protobridge.EventKind
	1, // 1: protobridge.EventOptions.visibility:type_name -> protobridge.Visibility
	4, // 2: protobridge.event:extendee -> google.protobuf.MessageOptions
	5, // 3: protobridge.broadcast:extendee -> google.protobuf.ServiceOptions
	3, // 4: protobridge.event:type_name -> protobridge.EventOptions
	2, // 5: protobridge.broadcast:type_name -> protobridge.BroadcastOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	4, // [4:6] is the sub-list for extension type_name
	2, // [2:4] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobridge_events_proto_init() }
func file_protobridge_events_proto_init() {
	if File_protobridge_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobridge_events_proto_rawDesc), len(file_protobridge_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_protobridge_events_proto_goTypes,
		DependencyIndexes: file_protobridge_events_proto_depIdxs,
		EnumInfos:         file_protobridge_events_proto_enumTypes,
		MessageInfos:      file_protobridge_events_proto_msgTypes,
		ExtensionInfos:    file_protobridge_events_proto_extTypes,
	}.Build()
	File_protobridge_events_proto = out.File
	file_protobridge_events_proto_goTypes = nil
	file_protobridge_events_proto_depIdxs = nil
}
