// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protobridge/options.proto

package protobridge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_protobridge_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "protobridge.required",
		Tag:           "varint,50001,opt,name=required",
		Filename:      "protobridge/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50010,
		Name:          "protobridge.required_headers",
		Tag:           "bytes,50010,rep,name=required_headers",
		Filename:      "protobridge/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50011,
		Name:          "protobridge.query_params_target",
		Tag:           "bytes,50011,opt,name=query_params_target",
		Filename:      "protobridge/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50012,
		Name:          "protobridge.exclude_auth",
		Tag:           "varint,50012,opt,name=exclude_auth",
		Filename:      "protobridge/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50020,
		Name:          "protobridge.auth_method",
		Tag:           "varint,50020,opt,name=auth_method",
		Filename:      "protobridge/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50021,
		Name:          "protobridge.sse",
		Tag:           "varint,50021,opt,name=sse",
		Filename:      "protobridge/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50022,
		Name:          "protobridge.ws_mode",
		Tag:           "bytes,50022,opt,name=ws_mode",
		Filename:      "protobridge/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50040,
		Name:          "protobridge.display_name",
		Tag:           "bytes,50040,opt,name=display_name",
		Filename:      "protobridge/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50041,
		Name:          "protobridge.path_prefix",
		Tag:           "bytes,50041,opt,name=path_prefix",
		Filename:      "protobridge/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50030,
		Name:          "protobridge.x_var_name",
		Tag:           "bytes,50030,opt,name=x_var_name",
		Filename:      "protobridge/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Marks a field as required. Validation is enforced at the REST layer.
	//
	// optional bool required = 50001;
	E_Required = &file_protobridge_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// Headers that will be extracted from the HTTP request and forwarded
	// as gRPC metadata. Repeated to allow multiple headers per method.
	//
	// repeated string required_headers = 50010;
	E_RequiredHeaders = &file_protobridge_options_proto_extTypes[1]
	// Field name in the request message that all query params map into.
	// All query param keys must match fields inside that nested message.
	//
	// optional string query_params_target = 50011;
	E_QueryParamsTarget = &file_protobridge_options_proto_extTypes[2]
	// If true, this method does not require authentication.
	//
	// optional bool exclude_auth = 50012;
	E_ExcludeAuth = &file_protobridge_options_proto_extTypes[3]
	// Marks this RPC as the authentication method for the entire API.
	// Input must accept HTTP headers, output must be a serializable User proto.
	// Exactly one method across all services must have this annotation.
	//
	// optional bool auth_method = 50020;
	E_AuthMethod = &file_protobridge_options_proto_extTypes[4]
	// Use Server-Sent Events instead of WebSocket for server-streaming RPCs.
	// Only valid on server-streaming methods. SSE is lighter than WebSocket
	// for one-way server→client push (e.g. live feeds, notifications).
	//
	// optional bool sse = 50021;
	E_Sse = &file_protobridge_options_proto_extTypes[5]
	// WebSocket connection mode for streaming RPCs.
	//
	//	"private"   – each WS connection opens its own gRPC stream with the
	//	              authenticated user_id in metadata. Backend knows exactly
	//	              who it's talking to. (default for auth endpoints)
	//	"broadcast" – all WS connections share the same event stream.
	//	              Backend pushes to everyone. No per-user routing.
	//
	// optional string ws_mode = 50022;
	E_WsMode = &file_protobridge_options_proto_extTypes[6]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// Human-readable name for this service group. Used as the OpenAPI tag name.
	// If not set, the proto service name is used.
	//
	// optional string display_name = 50040;
	E_DisplayName = &file_protobridge_options_proto_extTypes[7]
	// Path prefix prepended to all HTTP paths in this service.
	// Must start with "/" and not end with "/". Example: "/api/v1"
	//
	// optional string path_prefix = 50041;
	E_PathPrefix = &file_protobridge_options_proto_extTypes[8]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// Override the enum value name in OpenAPI / JSON output.
	//
	// optional string x_var_name = 50030;
	E_XVarName = &file_protobridge_options_proto_extTypes[9]
)

var File_protobridge_options_proto protoreflect.FileDescriptor

const file_protobridge_options_proto_rawDesc = "" +
	"\n" +
	"\x19protobridge/options.proto\x12\vprotobridge\x1a google/protobuf/descriptor.proto:;\n" +
	"\brequired\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\bR\brequired:K\n" +
	"\x10required_headers\x12\x1e.google.protobuf.MethodOptions\x18چ\x03 \x03(\tR\x0frequiredHeaders:P\n" +
	"\x13query_params_target\x12\x1e.google.protobuf.MethodOptions\x18ۆ\x03 \x01(\tR\x11queryParamsTarget:C\n" +
	"\fexclude_auth\x12\x1e.google.protobuf.MethodOptions\x18܆\x03 \x01(\bR\vexcludeAuth:A\n" +
	"\vauth_method\x12\x1e.google.protobuf.MethodOptions\x18\xe4\x86\x03 \x01(\bR\n" +
	"authMethod:2\n" +
	"\x03sse\x12\x1e.google.protobuf.MethodOptions\x18\xe5\x86\x03 \x01(\bR\x03sse:9\n" +
	"\aws_mode\x12\x1e.google.protobuf.MethodOptions\x18\xe6\x86\x03 \x01(\tR\x06wsMode:D\n" +
	"\fdisplay_name\x12\x1f.google.protobuf.ServiceOptions\x18\xf8\x86\x03 \x01(\tR\vdisplayName:B\n" +
	"\vpath_prefix\x12\x1f.google.protobuf.ServiceOptions\x18\xf9\x86\x03 \x01(\tR\n" +
	"pathPrefix:A\n" +
	"\n" +
	"x_var_name\x12!.google.protobuf.EnumValueOptions\x18\xee\x86\x03 \x01(\tR\bxVarNameB5Z3github.com/mrs1lentcz/protobridge/proto/protobridgeb\x06proto3"

var file_protobridge_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil),     // 0: google.protobuf.FieldOptions
	(*descriptorpb.MethodOptions)(nil),    // 1: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil),   // 2: google.protobuf.ServiceOptions
	(*descriptorpb.EnumValueOptions)(nil), // 3: google.protobuf.EnumValueOptions
}
var file_protobridge_options_proto_depIdxs = []int32{
	0,  // 0: protobridge.required:extendee -> google.protobuf.FieldOptions
	1,  // 1: protobridge.required_headers:extendee -> google.protobuf.MethodOptions
	1,  // 2: protobridge.query_params_target:extendee -> google.protobuf.MethodOptions
	1,  // 3: protobridge.exclude_auth:extendee -> google.protobuf.MethodOptions
	1,  // 4: protobridge.auth_method:extendee -> google.protobuf.MethodOptions
	1,  // 5: protobridge.sse:extendee -> google.protobuf.MethodOptions
	1,  // 6: protobridge.ws_mode:extendee -> google.protobuf.MethodOptions
	2,  // 7: protobridge.display_name:extendee -> google.protobuf.ServiceOptions
	2,  // 8: protobridge.path_prefix:extendee -> google.protobuf.ServiceOptions
	3,  // 9: protobridge.x_var_name:extendee -> google.protobuf.EnumValueOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	0,  // [0:10] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_protobridge_options_proto_init() }
func file_protobridge_options_proto_init() {
	if File_protobridge_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobridge_options_proto_rawDesc), len(file_protobridge_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 10,
			NumServices:   0,
		},
		GoTypes:           file_protobridge_options_proto_goTypes,
		DependencyIndexes: file_protobridge_options_proto_depIdxs,
		ExtensionInfos:    file_protobridge_options_proto_extTypes,
	}.Build()
	File_protobridge_options_proto = out.File
	file_protobridge_options_proto_goTypes = nil
	file_protobridge_options_proto_depIdxs = nil
}
