// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: test.proto

package testdata

import (
	_ "github.com/mrs1lentcz/protobridge/proto/protobridge"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_INACTIVE    Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_INACTIVE":    2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

// Color has no x_var_name aliases on any value — exercises the
// "no aliases, cache stores nil, second call returns from cache" path
// in enumAliases / reverseEnumAliases.
type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_COLOR_RED         Color = 1
	Color_COLOR_GREEN       Color = 2
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "COLOR_RED",
		2: "COLOR_GREEN",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"COLOR_RED":         1,
		"COLOR_GREEN":       2,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[1].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[1]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

type SimpleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=testdata.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleRequest) Reset() {
	*x = SimpleRequest{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleRequest) ProtoMessage() {}

func (x *SimpleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleRequest.ProtoReflect.Descriptor instead.
func (*SimpleRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimpleRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *SimpleRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type NestedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Paging        *Paging                `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedRequest) Reset() {
	*x = NestedRequest{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedRequest) ProtoMessage() {}

func (x *NestedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedRequest.ProtoReflect.Descriptor instead.
func (*NestedRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *NestedRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NestedRequest) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

type Paging struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paging) Reset() {
	*x = Paging{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paging) ProtoMessage() {}

func (x *Paging) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paging.ProtoReflect.Descriptor instead.
func (*Paging) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *Paging) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Paging) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type OneofResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*OneofResponse_Text
	//	*OneofResponse_Image
	Content       isOneofResponse_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofResponse) Reset() {
	*x = OneofResponse{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofResponse) ProtoMessage() {}

func (x *OneofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofResponse.ProtoReflect.Descriptor instead.
func (*OneofResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *OneofResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OneofResponse) GetContent() isOneofResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *OneofResponse) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Content.(*OneofResponse_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *OneofResponse) GetImage() *ImageContent {
	if x != nil {
		if x, ok := x.Content.(*OneofResponse_Image); ok {
			return x.Image
		}
	}
	return nil
}

type isOneofResponse_Content interface {
	isOneofResponse_Content()
}

type OneofResponse_Text struct {
	Text *TextContent `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type OneofResponse_Image struct {
	Image *ImageContent `protobuf:"bytes,3,opt,name=image,proto3,oneof"`
}

func (*OneofResponse_Text) isOneofResponse_Content() {}

func (*OneofResponse_Image) isOneofResponse_Content() {}

type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *TextContent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ImageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageContent) Reset() {
	*x = ImageContent{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageContent) ProtoMessage() {}

func (x *ImageContent) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageContent.ProtoReflect.Descriptor instead.
func (*ImageContent) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *ImageContent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageContent) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type SimpleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=testdata.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleResponse) Reset() {
	*x = SimpleResponse{}
	mi := &file_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleResponse) ProtoMessage() {}

func (x *SimpleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleResponse.ProtoReflect.Descriptor instead.
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *SimpleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SimpleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimpleResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

// AllTypesRequest is used for testing parseFieldValue and isZero with all
// common proto scalar types.
type AllTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrVal        string                 `protobuf:"bytes,1,opt,name=str_val,json=strVal,proto3" json:"str_val,omitempty"`
	BoolVal       bool                   `protobuf:"varint,2,opt,name=bool_val,json=boolVal,proto3" json:"bool_val,omitempty"`
	Int32Val      int32                  `protobuf:"varint,3,opt,name=int32_val,json=int32Val,proto3" json:"int32_val,omitempty"`
	Int64Val      int64                  `protobuf:"varint,4,opt,name=int64_val,json=int64Val,proto3" json:"int64_val,omitempty"`
	Uint32Val     uint32                 `protobuf:"varint,5,opt,name=uint32_val,json=uint32Val,proto3" json:"uint32_val,omitempty"`
	Uint64Val     uint64                 `protobuf:"varint,6,opt,name=uint64_val,json=uint64Val,proto3" json:"uint64_val,omitempty"`
	FloatVal      float32                `protobuf:"fixed32,7,opt,name=float_val,json=floatVal,proto3" json:"float_val,omitempty"`
	DoubleVal     float64                `protobuf:"fixed64,8,opt,name=double_val,json=doubleVal,proto3" json:"double_val,omitempty"`
	BytesVal      []byte                 `protobuf:"bytes,9,opt,name=bytes_val,json=bytesVal,proto3" json:"bytes_val,omitempty"`
	EnumVal       Status                 `protobuf:"varint,10,opt,name=enum_val,json=enumVal,proto3,enum=testdata.Status" json:"enum_val,omitempty"`
	MsgVal        *Paging                `protobuf:"bytes,11,opt,name=msg_val,json=msgVal,proto3" json:"msg_val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllTypesRequest) Reset() {
	*x = AllTypesRequest{}
	mi := &file_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTypesRequest) ProtoMessage() {}

func (x *AllTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTypesRequest.ProtoReflect.Descriptor instead.
func (*AllTypesRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *AllTypesRequest) GetStrVal() string {
	if x != nil {
		return x.StrVal
	}
	return ""
}

func (x *AllTypesRequest) GetBoolVal() bool {
	if x != nil {
		return x.BoolVal
	}
	return false
}

func (x *AllTypesRequest) GetInt32Val() int32 {
	if x != nil {
		return x.Int32Val
	}
	return 0
}

func (x *AllTypesRequest) GetInt64Val() int64 {
	if x != nil {
		return x.Int64Val
	}
	return 0
}

func (x *AllTypesRequest) GetUint32Val() uint32 {
	if x != nil {
		return x.Uint32Val
	}
	return 0
}

func (x *AllTypesRequest) GetUint64Val() uint64 {
	if x != nil {
		return x.Uint64Val
	}
	return 0
}

func (x *AllTypesRequest) GetFloatVal() float32 {
	if x != nil {
		return x.FloatVal
	}
	return 0
}

func (x *AllTypesRequest) GetDoubleVal() float64 {
	if x != nil {
		return x.DoubleVal
	}
	return 0
}

func (x *AllTypesRequest) GetBytesVal() []byte {
	if x != nil {
		return x.BytesVal
	}
	return nil
}

func (x *AllTypesRequest) GetEnumVal() Status {
	if x != nil {
		return x.EnumVal
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *AllTypesRequest) GetMsgVal() *Paging {
	if x != nil {
		return x.MsgVal
	}
	return nil
}

// QueryRequest has a nested query params message with diverse types.
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Params        *QueryParams           `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *QueryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryRequest) GetParams() *QueryParams {
	if x != nil {
		return x.Params
	}
	return nil
}

// EnumContainerRequest exercises repeated and map enum field rewriting in
// the JSON enum-alias prepass.
type EnumContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []Status               `protobuf:"varint,1,rep,packed,name=statuses,proto3,enum=testdata.Status" json:"statuses,omitempty"`
	ByName        map[string]Status      `protobuf:"bytes,2,rep,name=by_name,json=byName,proto3" json:"by_name,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=testdata.Status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumContainerRequest) Reset() {
	*x = EnumContainerRequest{}
	mi := &file_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumContainerRequest) ProtoMessage() {}

func (x *EnumContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumContainerRequest.ProtoReflect.Descriptor instead.
func (*EnumContainerRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{9}
}

func (x *EnumContainerRequest) GetStatuses() []Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *EnumContainerRequest) GetByName() map[string]Status {
	if x != nil {
		return x.ByName
	}
	return nil
}

// MapOnlyEnumRequest forces the descriptor walker through the map branch of
// descriptorHasAliases (no preceding scalar/repeated enum field that would
// short-circuit the walk).
type MapOnlyEnumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]Status      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=testdata.Status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapOnlyEnumRequest) Reset() {
	*x = MapOnlyEnumRequest{}
	mi := &file_test_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapOnlyEnumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapOnlyEnumRequest) ProtoMessage() {}

func (x *MapOnlyEnumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapOnlyEnumRequest.ProtoReflect.Descriptor instead.
func (*MapOnlyEnumRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{10}
}

func (x *MapOnlyEnumRequest) GetEntries() map[string]Status {
	if x != nil {
		return x.Entries
	}
	return nil
}

// WrapperRequest forces the descriptor walker through the nested-message
// branch of fieldHasAliases — its only field is a message that itself
// transitively carries an alias-bearing enum.
type WrapperRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inner         *SimpleResponse        `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapperRequest) Reset() {
	*x = WrapperRequest{}
	mi := &file_test_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapperRequest) ProtoMessage() {}

func (x *WrapperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapperRequest.ProtoReflect.Descriptor instead.
func (*WrapperRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{11}
}

func (x *WrapperRequest) GetInner() *SimpleResponse {
	if x != nil {
		return x.Inner
	}
	return nil
}

// ColorRequest carries an alias-free enum field so the cache-nil branch
// in enumAliases / reverseEnumAliases is hit on the second call.
type ColorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         Color                  `protobuf:"varint,1,opt,name=color,proto3,enum=testdata.Color" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorRequest) Reset() {
	*x = ColorRequest{}
	mi := &file_test_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorRequest) ProtoMessage() {}

func (x *ColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorRequest.ProtoReflect.Descriptor instead.
func (*ColorRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{12}
}

func (x *ColorRequest) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_COLOR_UNSPECIFIED
}

type QueryParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=testdata.Status" json:"status,omitempty"`
	PageSize      uint32                 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor        uint64                 `protobuf:"varint,7,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Weight        float64                `protobuf:"fixed64,8,opt,name=weight,proto3" json:"weight,omitempty"`
	Page          int32                  `protobuf:"varint,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParams) Reset() {
	*x = QueryParams{}
	mi := &file_test_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParams) ProtoMessage() {}

func (x *QueryParams) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParams.ProtoReflect.Descriptor instead.
func (*QueryParams) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{13}
}

func (x *QueryParams) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *QueryParams) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *QueryParams) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryParams) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QueryParams) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *QueryParams) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryParams) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *QueryParams) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *QueryParams) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\btestdata\x1a\x19protobridge/options.proto\"_\n" +
	"\rSimpleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12(\n" +
	"\x06status\x18\x03 \x01(\x0e2\x10.testdata.StatusR\x06status\"O\n" +
	"\rNestedRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12(\n" +
	"\x06paging\x18\x02 \x01(\v2\x10.testdata.PagingR\x06paging\"2\n" +
	"\x06Paging\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x87\x01\n" +
	"\rOneofResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04text\x18\x02 \x01(\v2\x15.testdata.TextContentH\x00R\x04text\x12.\n" +
	"\x05image\x18\x03 \x01(\v2\x16.testdata.ImageContentH\x00R\x05imageB\t\n" +
	"\acontent\"!\n" +
	"\vTextContent\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"6\n" +
	"\fImageContent\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\"^\n" +
	"\x0eSimpleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x06status\x18\x03 \x01(\x0e2\x10.testdata.StatusR\x06status\"\xee\x02\n" +
	"\x0fAllTypesRequest\x12\x17\n" +
	"\astr_val\x18\x01 \x01(\tR\x06strVal\x12\x19\n" +
	"\bbool_val\x18\x02 \x01(\bR\aboolVal\x12\x1b\n" +
	"\tint32_val\x18\x03 \x01(\x05R\bint32Val\x12\x1b\n" +
	"\tint64_val\x18\x04 \x01(\x03R\bint64Val\x12\x1d\n" +
	"\n" +
	"uint32_val\x18\x05 \x01(\rR\tuint32Val\x12\x1d\n" +
	"\n" +
	"uint64_val\x18\x06 \x01(\x04R\tuint64Val\x12\x1b\n" +
	"\tfloat_val\x18\a \x01(\x02R\bfloatVal\x12\x1d\n" +
	"\n" +
	"double_val\x18\b \x01(\x01R\tdoubleVal\x12\x1b\n" +
	"\tbytes_val\x18\t \x01(\fR\bbytesVal\x12+\n" +
	"\benum_val\x18\n" +
	" \x01(\x0e2\x10.testdata.StatusR\aenumVal\x12)\n" +
	"\amsg_val\x18\v \x01(\v2\x10.testdata.PagingR\x06msgVal\"M\n" +
	"\fQueryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x06params\x18\x02 \x01(\v2\x15.testdata.QueryParamsR\x06params\"\xd6\x01\n" +
	"\x14EnumContainerRequest\x12,\n" +
	"\bstatuses\x18\x01 \x03(\x0e2\x10.testdata.StatusR\bstatuses\x12C\n" +
	"\aby_name\x18\x02 \x03(\v2*.testdata.EnumContainerRequest.ByNameEntryR\x06byName\x1aK\n" +
	"\vByNameEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\x0e2\x10.testdata.StatusR\x05value:\x028\x01\"\xa7\x01\n" +
	"\x12MapOnlyEnumRequest\x12C\n" +
	"\aentries\x18\x01 \x03(\v2).testdata.MapOnlyEnumRequest.EntriesEntryR\aentries\x1aL\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\x0e2\x10.testdata.StatusR\x05value:\x028\x01\"@\n" +
	"\x0eWrapperRequest\x12.\n" +
	"\x05inner\x18\x01 \x01(\v2\x18.testdata.SimpleResponseR\x05inner\"5\n" +
	"\fColorRequest\x12%\n" +
	"\x05color\x18\x01 \x01(\x0e2\x0f.testdata.ColorR\x05color\"\xf6\x01\n" +
	"\vQueryParams\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x12(\n" +
	"\x06status\x18\x05 \x01(\x0e2\x10.testdata.StatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\rR\bpageSize\x12\x16\n" +
	"\x06cursor\x18\a \x01(\x04R\x06cursor\x12\x16\n" +
	"\x06weight\x18\b \x01(\x01R\x06weight\x12\x12\n" +
	"\x04page\x18\t \x01(\x05R\x04page*b\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\rSTATUS_ACTIVE\x10\x01\x1a\n" +
	"\xf2\xb6\x18\x06active\x12!\n" +
	"\x0fSTATUS_INACTIVE\x10\x02\x1a\f\xf2\xb6\x18\binactive*>\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCOLOR_RED\x10\x01\x12\x0f\n" +
	"\vCOLOR_GREEN\x10\x02B4Z2github.com/mrs1lentcz/protobridge/runtime/testdatab\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_test_proto_goTypes = []any{
	(Status)(0),                  // 0: testdata.Status
	(Color)(0),                   // 1: testdata.Color
	(*SimpleRequest)(nil),        // 2: testdata.SimpleRequest
	(*NestedRequest)(nil),        // 3: testdata.NestedRequest
	(*Paging)(nil),               // 4: testdata.Paging
	(*OneofResponse)(nil),        // 5: testdata.OneofResponse
	(*TextContent)(nil),          // 6: testdata.TextContent
	(*ImageContent)(nil),         // 7: testdata.ImageContent
	(*SimpleResponse)(nil),       // 8: testdata.SimpleResponse
	(*AllTypesRequest)(nil),      // 9: testdata.AllTypesRequest
	(*QueryRequest)(nil),         // 10: testdata.QueryRequest
	(*EnumContainerRequest)(nil), // 11: testdata.EnumContainerRequest
	(*MapOnlyEnumRequest)(nil),   // 12: testdata.MapOnlyEnumRequest
	(*WrapperRequest)(nil),       // 13: testdata.WrapperRequest
	(*ColorRequest)(nil),         // 14: testdata.ColorRequest
	(*QueryParams)(nil),          // 15: testdata.QueryParams
	nil,                          // 16: testdata.EnumContainerRequest.ByNameEntry
	nil,                          // 17: testdata.MapOnlyEnumRequest.EntriesEntry
}
var file_test_proto_depIdxs = []int32{
	0,  // 0: testdata.SimpleRequest.status:type_name -> testdata.Status
	4,  // 1: testdata.NestedRequest.paging:type_name -> testdata.Paging
	6,  // 2: testdata.OneofResponse.text:type_name -> testdata.TextContent
	7,  // 3: testdata.OneofResponse.image:type_name -> testdata.ImageContent
	0,  // 4: testdata.SimpleResponse.status:type_name -> testdata.Status
	0,  // 5: testdata.AllTypesRequest.enum_val:type_name -> testdata.Status
	4,  // 6: testdata.AllTypesRequest.msg_val:type_name -> testdata.Paging
	15, // 7: testdata.QueryRequest.params:type_name -> testdata.QueryParams
	0,  // 8: testdata.EnumContainerRequest.statuses:type_name -> testdata.Status
	16, // 9: testdata.EnumContainerRequest.by_name:type_name -> testdata.EnumContainerRequest.ByNameEntry
	17, // 10: testdata.MapOnlyEnumRequest.entries:type_name -> testdata.MapOnlyEnumRequest.EntriesEntry
	8,  // 11: testdata.WrapperRequest.inner:type_name -> testdata.SimpleResponse
	1,  // 12: testdata.ColorRequest.color:type_name -> testdata.Color
	0,  // 13: testdata.QueryParams.status:type_name -> testdata.Status
	0,  // 14: testdata.EnumContainerRequest.ByNameEntry.value:type_name -> testdata.Status
	0,  // 15: testdata.MapOnlyEnumRequest.EntriesEntry.value:type_name -> testdata.Status
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_test_proto_msgTypes[3].OneofWrappers = []any{
		(*OneofResponse_Text)(nil),
		(*OneofResponse_Image)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
