FROM golang:latest AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /rest-proxy ./bench/rest-proxy/

FROM alpine:latest
COPY --from=build /rest-proxy /rest-proxy
EXPOSE 8080
ENTRYPOINT ["/rest-proxy"]
