package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/mrs1lentcz/protobridge/internal/parser"
)

// GenerateAsyncAPI produces an AsyncAPI 3.0 YAML spec for all streaming RPCs.
// Returns empty string if there are no streaming endpoints.
//
// Schema IDs are computed the same way as in GenerateOpenAPI: short name
// when unique across the emitted set, PascalCase-qualified FQN when two
// messages share a short name across proto packages. Message IDs under
// components.messages match the schema IDs, so `$ref: '#/components/
// messages/<id>'` and `$ref: '#/components/schemas/<id>'` are always
// consistent for the same type.
func GenerateAsyncAPI(api *parser.ParsedAPI) string {
	var channels []asyncChannel
	for _, svc := range api.Services {
		for _, m := range svc.Methods {
			if m.StreamType == parser.StreamUnary || m.HTTPMethod == "" {
				continue
			}
			channels = append(channels, asyncChannel{
				svc:    svc,
				method: m,
			})
		}
	}

	if len(channels) == 0 {
		return ""
	}

	index := buildMessageIndex(api)
	schemas := collectAsyncSchemas(channels, index)
	ids := buildSchemaIDs(schemas)

	var b strings.Builder

	b.WriteString("asyncapi: '3.0.0'\n")
	b.WriteString("info:\n")
	b.WriteString("  title: protobridge WebSocket API\n")
	b.WriteString("  version: '1.0.0'\n")
	b.WriteString("  description: WebSocket endpoints generated by protobridge for streaming gRPC methods.\n")

	// Servers
	b.WriteString("servers:\n")
	b.WriteString("  default:\n")
	b.WriteString("    host: localhost:8080\n")
	b.WriteString("    protocol: ws\n")

	// Channels – messages reference #/components/messages/*
	b.WriteString("channels:\n")
	for _, ch := range channels {
		writeAsyncChannel(&b, ch, ids)
	}

	// Operations
	b.WriteString("operations:\n")
	for _, ch := range channels {
		writeAsyncOperation(&b, ch)
	}

	// Components
	b.WriteString("components:\n")

	// Messages – each wraps a schema via payload.$ref. The set mirrors the
	// top-level channel message types (inputs for client/bidi, outputs for
	// server/bidi), deduplicated on FullName so two same-named messages
	// from different proto packages stay distinct.
	messages := collectAsyncMessages(channels)
	b.WriteString("  messages:\n")
	for _, mt := range messages {
		id := schemaRefForType(mt, ids)
		fmt.Fprintf(&b, "    %s:\n", id)
		fmt.Fprintf(&b, "      payload:\n")
		fmt.Fprintf(&b, "        $ref: '#/components/schemas/%s'\n", id)
	}

	// Schemas – include all referenced types transitively
	b.WriteString("  schemas:\n")
	for _, mt := range schemas {
		writeSchema(&b, mt, index, ids)
	}

	return b.String()
}

type asyncChannel struct {
	svc    *parser.Service
	method *parser.Method
}

func asyncChannelID(svc *parser.Service, m *parser.Method) string {
	return toLowerCamel(svc.Name) + toPascalCase(m.Name)
}

func writeAsyncChannel(b *strings.Builder, ch asyncChannel, ids map[string]string) {
	id := asyncChannelID(ch.svc, ch.method)
	m := ch.method

	fmt.Fprintf(b, "  %s:\n", id)
	fmt.Fprintf(b, "    address: %s\n", m.HTTPPath)
	fmt.Fprintf(b, "    description: '%s.%s (%s)'\n", ch.svc.Name, m.Name, streamLabel(m.StreamType))
	fmt.Fprintf(b, "    messages:\n")

	// Collect the unique set of message types for this channel, keyed on
	// FullName so cross-package same-named messages don't collapse.
	seen := make(map[string]bool)
	var types []*parser.MessageType
	addMsg := func(mt *parser.MessageType) {
		if mt == nil || mt.FullName == "" || seen[mt.FullName] {
			return
		}
		seen[mt.FullName] = true
		types = append(types, mt)
	}

	switch m.StreamType {
	case parser.StreamServer:
		addMsg(m.OutputType)
	case parser.StreamClient:
		addMsg(m.InputType)
	case parser.StreamBidi:
		addMsg(m.InputType)
		addMsg(m.OutputType)
	}

	for _, mt := range types {
		id := schemaRefForType(mt, ids)
		fmt.Fprintf(b, "      %s:\n", id)
		fmt.Fprintf(b, "        $ref: '#/components/messages/%s'\n", id)
	}
}

func writeAsyncOperation(b *strings.Builder, ch asyncChannel) {
	id := asyncChannelID(ch.svc, ch.method)
	m := ch.method

	switch m.StreamType {
	case parser.StreamServer:
		fmt.Fprintf(b, "  %sReceive:\n", id)
		fmt.Fprintf(b, "    action: receive\n")
		fmt.Fprintf(b, "    channel:\n")
		fmt.Fprintf(b, "      $ref: '#/channels/%s'\n", id)
		fmt.Fprintf(b, "    summary: Receive %s events from server\n", m.OutputType.Name)
	case parser.StreamClient:
		fmt.Fprintf(b, "  %sSend:\n", id)
		fmt.Fprintf(b, "    action: send\n")
		fmt.Fprintf(b, "    channel:\n")
		fmt.Fprintf(b, "      $ref: '#/channels/%s'\n", id)
		fmt.Fprintf(b, "    summary: Send %s messages to server\n", m.InputType.Name)
	case parser.StreamBidi:
		fmt.Fprintf(b, "  %sSend:\n", id)
		fmt.Fprintf(b, "    action: send\n")
		fmt.Fprintf(b, "    channel:\n")
		fmt.Fprintf(b, "      $ref: '#/channels/%s'\n", id)
		fmt.Fprintf(b, "    summary: Send %s messages\n", m.InputType.Name)
		fmt.Fprintf(b, "  %sReceive:\n", id)
		fmt.Fprintf(b, "    action: receive\n")
		fmt.Fprintf(b, "    channel:\n")
		fmt.Fprintf(b, "      $ref: '#/channels/%s'\n", id)
		fmt.Fprintf(b, "    summary: Receive %s messages\n", m.OutputType.Name)
	}
}

// collectAsyncMessages returns deduplicated top-level channel messages.
// Dedup key is FullName so cross-package same-named messages stay distinct.
func collectAsyncMessages(channels []asyncChannel) []*parser.MessageType {
	seen := make(map[string]bool)
	var out []*parser.MessageType
	add := func(mt *parser.MessageType) {
		if mt == nil || mt.FullName == "" || seen[mt.FullName] {
			return
		}
		seen[mt.FullName] = true
		out = append(out, mt)
	}
	for _, ch := range channels {
		m := ch.method
		switch m.StreamType {
		case parser.StreamServer:
			add(m.OutputType)
		case parser.StreamClient:
			add(m.InputType)
		case parser.StreamBidi:
			add(m.InputType)
			add(m.OutputType)
		}
	}
	return out
}

// collectAsyncSchemas returns every MessageType reachable from channel
// input/output types, in BFS discovery order. WKTs and map entries are
// skipped (rendered inline / collapsed to additionalProperties downstream).
// Follows MESSAGE field targets through the FQN index so cross-package
// messages with duplicate short names stay distinct.
func collectAsyncSchemas(channels []asyncChannel, index map[string]*parser.MessageType) []*parser.MessageType {
	seen := make(map[string]bool)
	var out []*parser.MessageType
	var queue []*parser.MessageType

	enqueue := func(mt *parser.MessageType) {
		if mt == nil || mt.FullName == "" {
			return
		}
		if isWellKnown(mt.FullName) || mt.MapEntry {
			return
		}
		if seen[mt.FullName] {
			return
		}
		seen[mt.FullName] = true
		queue = append(queue, mt)
	}

	for _, ch := range channels {
		enqueue(ch.method.InputType)
		enqueue(ch.method.OutputType)
	}

	for len(queue) > 0 {
		mt := queue[0]
		queue = queue[1:]
		out = append(out, mt)
		for _, f := range mt.Fields {
			if f.Type != descriptorpb.FieldDescriptorProto_TYPE_MESSAGE || f.TypeName == "" {
				continue
			}
			if isWellKnown(f.TypeName) {
				continue
			}
			target, ok := index[f.TypeName]
			if !ok {
				continue
			}
			if target.MapEntry {
				// Follow into value-field target instead of emitting the
				// synthetic entry message.
				for _, vf := range target.Fields {
					if vf.Number == 2 && vf.Type == descriptorpb.FieldDescriptorProto_TYPE_MESSAGE && !isWellKnown(vf.TypeName) {
						if next, ok := index[vf.TypeName]; ok {
							enqueue(next)
						}
					}
				}
				continue
			}
			enqueue(target)
		}
	}
	return out
}

func streamLabel(st parser.StreamType) string {
	switch st {
	case parser.StreamServer:
		return "server streaming"
	case parser.StreamClient:
		return "client streaming"
	case parser.StreamBidi:
		return "bidirectional streaming"
	default:
		return "unary"
	}
}
