package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/mrs1lentcz/protobridge/internal/parser"
)

// GenerateAsyncAPI produces an AsyncAPI 3.0 YAML spec for all streaming RPCs.
// Returns empty string if there are no streaming endpoints.
func GenerateAsyncAPI(api *parser.ParsedAPI) string {
	var channels []asyncChannel
	for _, svc := range api.Services {
		for _, m := range svc.Methods {
			if m.StreamType == parser.StreamUnary {
				continue
			}
			channels = append(channels, asyncChannel{
				svc:    svc,
				method: m,
			})
		}
	}

	if len(channels) == 0 {
		return ""
	}

	var b strings.Builder

	b.WriteString("asyncapi: '3.0.0'\n")
	b.WriteString("info:\n")
	b.WriteString("  title: protobridge WebSocket API\n")
	b.WriteString("  version: '1.0.0'\n")
	b.WriteString("  description: WebSocket endpoints generated by protobridge for streaming gRPC methods.\n")

	// Servers
	b.WriteString("servers:\n")
	b.WriteString("  default:\n")
	b.WriteString("    host: localhost:8080\n")
	b.WriteString("    protocol: ws\n")

	// Channels – messages reference #/components/messages/*
	b.WriteString("channels:\n")
	for _, ch := range channels {
		writeAsyncChannel(&b, ch)
	}

	// Operations
	b.WriteString("operations:\n")
	for _, ch := range channels {
		writeAsyncOperation(&b, ch)
	}

	// Components
	b.WriteString("components:\n")

	// Messages – each wraps a schema via payload.$ref
	messages := collectAsyncMessages(channels)
	b.WriteString("  messages:\n")
	for _, name := range messages {
		fmt.Fprintf(&b, "    %s:\n", name)
		fmt.Fprintf(&b, "      payload:\n")
		fmt.Fprintf(&b, "        $ref: '#/components/schemas/%s'\n", name)
	}

	// Schemas – include all referenced types transitively
	schemas := collectAsyncSchemas(channels, api)
	b.WriteString("  schemas:\n")
	for _, mt := range schemas {
		writeSchema(&b, mt)
	}

	return b.String()
}

type asyncChannel struct {
	svc    *parser.Service
	method *parser.Method
}

func asyncChannelID(svc *parser.Service, m *parser.Method) string {
	return toLowerCamel(svc.Name) + toPascalCase(m.Name)
}

func writeAsyncChannel(b *strings.Builder, ch asyncChannel) {
	id := asyncChannelID(ch.svc, ch.method)
	m := ch.method

	fmt.Fprintf(b, "  %s:\n", id)
	fmt.Fprintf(b, "    address: %s\n", m.HTTPPath)
	fmt.Fprintf(b, "    description: '%s.%s (%s)'\n", ch.svc.Name, m.Name, streamLabel(m.StreamType))
	fmt.Fprintf(b, "    messages:\n")

	// Collect unique message names for this channel.
	seen := make(map[string]bool)
	var names []string
	addMsg := func(mt *parser.MessageType) {
		if mt != nil && !seen[mt.Name] {
			seen[mt.Name] = true
			names = append(names, mt.Name)
		}
	}

	switch m.StreamType {
	case parser.StreamServer:
		addMsg(m.OutputType)
	case parser.StreamClient:
		addMsg(m.InputType)
	case parser.StreamBidi:
		addMsg(m.InputType)
		addMsg(m.OutputType)
	}

	for _, name := range names {
		fmt.Fprintf(b, "      %s:\n", name)
		fmt.Fprintf(b, "        $ref: '#/components/messages/%s'\n", name)
	}
}

func writeAsyncOperation(b *strings.Builder, ch asyncChannel) {
	id := asyncChannelID(ch.svc, ch.method)
	m := ch.method

	switch m.StreamType {
	case parser.StreamServer:
		fmt.Fprintf(b, "  %sReceive:\n", id)
		fmt.Fprintf(b, "    action: receive\n")
		fmt.Fprintf(b, "    channel:\n")
		fmt.Fprintf(b, "      $ref: '#/channels/%s'\n", id)
		fmt.Fprintf(b, "    summary: Receive %s events from server\n", m.OutputType.Name)
	case parser.StreamClient:
		fmt.Fprintf(b, "  %sSend:\n", id)
		fmt.Fprintf(b, "    action: send\n")
		fmt.Fprintf(b, "    channel:\n")
		fmt.Fprintf(b, "      $ref: '#/channels/%s'\n", id)
		fmt.Fprintf(b, "    summary: Send %s messages to server\n", m.InputType.Name)
	case parser.StreamBidi:
		fmt.Fprintf(b, "  %sSend:\n", id)
		fmt.Fprintf(b, "    action: send\n")
		fmt.Fprintf(b, "    channel:\n")
		fmt.Fprintf(b, "      $ref: '#/channels/%s'\n", id)
		fmt.Fprintf(b, "    summary: Send %s messages\n", m.InputType.Name)
		fmt.Fprintf(b, "  %sReceive:\n", id)
		fmt.Fprintf(b, "    action: receive\n")
		fmt.Fprintf(b, "    channel:\n")
		fmt.Fprintf(b, "      $ref: '#/channels/%s'\n", id)
		fmt.Fprintf(b, "    summary: Receive %s messages\n", m.OutputType.Name)
	}
}

// collectAsyncMessages returns deduplicated message type names used in channels.
func collectAsyncMessages(channels []asyncChannel) []string {
	seen := make(map[string]bool)
	var names []string
	add := func(mt *parser.MessageType) {
		if mt != nil && !seen[mt.Name] {
			seen[mt.Name] = true
			names = append(names, mt.Name)
		}
	}
	for _, ch := range channels {
		m := ch.method
		switch m.StreamType {
		case parser.StreamServer:
			add(m.OutputType)
		case parser.StreamClient:
			add(m.InputType)
		case parser.StreamBidi:
			add(m.InputType)
			add(m.OutputType)
		}
	}
	return names
}

// collectAsyncSchemas returns all MessageTypes needed for schemas, including
// types referenced transitively by message fields (e.g. TaskEvent → Task).
func collectAsyncSchemas(channels []asyncChannel, api *parser.ParsedAPI) []*parser.MessageType {
	seen := make(map[string]bool)
	var result []*parser.MessageType

	var enqueue func(mt *parser.MessageType)
	enqueue = func(mt *parser.MessageType) {
		if mt == nil || seen[mt.Name] {
			return
		}
		seen[mt.Name] = true
		result = append(result, mt)
		// Follow message-typed fields to collect transitive deps.
		for _, f := range mt.Fields {
			if f.Type == descriptorpb.FieldDescriptorProto_TYPE_MESSAGE && f.TypeName != "" {
				parts := strings.Split(f.TypeName, ".")
				refName := parts[len(parts)-1]
				if ref := findMessageTypeInAPI(api, refName); ref != nil {
					enqueue(ref)
				}
			}
		}
	}

	for _, ch := range channels {
		enqueue(ch.method.InputType)
		enqueue(ch.method.OutputType)
	}
	return result
}

// findMessageTypeInAPI searches all services' input/output types for a
// MessageType with the given unqualified name.
func findMessageTypeInAPI(api *parser.ParsedAPI, name string) *parser.MessageType {
	for _, svc := range api.Services {
		for _, m := range svc.Methods {
			if m.InputType != nil && m.InputType.Name == name {
				return m.InputType
			}
			if m.OutputType != nil && m.OutputType.Name == name {
				return m.OutputType
			}
		}
	}
	return nil
}

func streamLabel(st parser.StreamType) string {
	switch st {
	case parser.StreamServer:
		return "server streaming"
	case parser.StreamClient:
		return "client streaming"
	case parser.StreamBidi:
		return "bidirectional streaming"
	default:
		return "unary"
	}
}
