package generator

import (
	"fmt"
	"strings"

	"github.com/mrs1lentcz/protobridge/internal/parser"
)

// GenerateDockerfile produces a multi-stage Dockerfile for the generated proxy.
func GenerateDockerfile() string {
	return `# Generated by protoc-gen-protobridge. Adjust as needed.

FROM golang:1.23-alpine AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /protobridge .

FROM gcr.io/distroless/static-debian12

COPY --from=build /protobridge /protobridge

EXPOSE 8080

ENTRYPOINT ["/protobridge"]
`
}

// GenerateK8sManifest produces a minimal Kubernetes Deployment + Service
// for the generated proxy.
func GenerateK8sManifest(api *parser.ParsedAPI) string {
	var b strings.Builder

	b.WriteString("# Generated by protoc-gen-protobridge. Adjust as needed.\n")
	b.WriteString("apiVersion: apps/v1\n")
	b.WriteString("kind: Deployment\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: protobridge\n")
	b.WriteString("  labels:\n")
	b.WriteString("    app: protobridge\n")
	b.WriteString("spec:\n")
	b.WriteString("  replicas: 2\n")
	b.WriteString("  selector:\n")
	b.WriteString("    matchLabels:\n")
	b.WriteString("      app: protobridge\n")
	b.WriteString("  template:\n")
	b.WriteString("    metadata:\n")
	b.WriteString("      labels:\n")
	b.WriteString("        app: protobridge\n")
	b.WriteString("    spec:\n")
	b.WriteString("      containers:\n")
	b.WriteString("        - name: protobridge\n")
	b.WriteString("          image: protobridge:latest\n")
	b.WriteString("          ports:\n")
	b.WriteString("            - containerPort: 8080\n")
	b.WriteString("          env:\n")
	b.WriteString("            - name: PROTOBRIDGE_PORT\n")
	b.WriteString("              value: \"8080\"\n")

	// Generate env vars for each service.
	for _, svc := range api.Services {
		envKey := "PROTOBRIDGE_" + toScreamingSnake(svc.Name) + "_ADDR"
		fmt.Fprintf(&b, "            - name: %s\n", envKey)
		fmt.Fprintf(&b, "              value: \"%s:50051\"  # TODO: set actual address\n", toSnakeCase(svc.Name))
	}
	if api.AuthMethod != nil {
		// Check if auth service already covered above.
		found := false
		for _, svc := range api.Services {
			if svc.Name == api.AuthMethod.ServiceName {
				found = true
				break
			}
		}
		if !found {
			envKey := "PROTOBRIDGE_" + toScreamingSnake(api.AuthMethod.ServiceName) + "_ADDR"
			fmt.Fprintf(&b, "            - name: %s\n", envKey)
			fmt.Fprintf(&b, "              value: \"%s:50051\"  # TODO: set actual address\n", toSnakeCase(api.AuthMethod.ServiceName))
		}
	}

	b.WriteString("          readinessProbe:\n")
	b.WriteString("            httpGet:\n")
	b.WriteString("              path: /healthz\n")
	b.WriteString("              port: 8080\n")
	b.WriteString("            initialDelaySeconds: 5\n")
	b.WriteString("            periodSeconds: 10\n")
	b.WriteString("          livenessProbe:\n")
	b.WriteString("            httpGet:\n")
	b.WriteString("              path: /healthz\n")
	b.WriteString("              port: 8080\n")
	b.WriteString("            initialDelaySeconds: 10\n")
	b.WriteString("            periodSeconds: 30\n")

	b.WriteString("---\n")
	b.WriteString("apiVersion: v1\n")
	b.WriteString("kind: Service\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: protobridge\n")
	b.WriteString("spec:\n")
	b.WriteString("  selector:\n")
	b.WriteString("    app: protobridge\n")
	b.WriteString("  ports:\n")
	b.WriteString("    - port: 80\n")
	b.WriteString("      targetPort: 8080\n")
	b.WriteString("      protocol: TCP\n")
	b.WriteString("  type: ClusterIP\n")

	return b.String()
}
