package generator

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/mrs1lentcz/protobridge/internal/parser"
)

var serviceFileTmpl = template.Must(template.New("service").Parse(`// Code generated by protoc-gen-protobridge. DO NOT EDIT.

package main

import (
	"context"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/mrs1lentcz/gox/grpcx"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/mrs1lentcz/protobridge/runtime"
	pb "{{ .ProtoImport }}"
)

func register{{ .ServiceName }}(r chi.Router, conn *grpc.ClientConn, addr string, pool *grpcx.Pool, auth runtime.AuthFunc) {
	client := pb.New{{ .ServiceName }}Client(conn)
	{{ range .Methods }}
	r.{{ .ChiMethod }}("{{ .ChiPath }}", {{ .HandlerFuncName }}(client, addr, pool, auth))
	{{- end }}
}
{{ range .Methods }}
func {{ .HandlerFuncName }}(client pb.{{ $.ServiceName }}Client, addr string, pool *grpcx.Pool, auth runtime.AuthFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		{{ if not .ExcludeAuth }}
		// Auth
		userData, err := auth(ctx, r)
		if err != nil {
			runtime.WriteAuthError(w, err)
			return
		}
		ctx = runtime.SetUserMetadata(ctx, userData)
		{{ end }}
		// Path params → metadata
		md := metadata.MD{}
		{{ range .PathParams -}}
		md.Set("{{ . }}", chi.URLParam(r, "{{ . }}"))
		{{ end }}
		// Required headers
		{{ range .RequiredHeaders -}}
		{{ .VarName }} := r.Header.Get("{{ .HeaderName }}")
		if {{ .VarName }} == "" {
			runtime.WriteError(w, http.StatusBadRequest, "INVALID_ARGUMENT", "missing required header: {{ .HeaderName }}")
			return
		}
		md.Set("{{ .HeaderName }}", {{ .VarName }})
		{{ end }}
		ctx = metadata.NewOutgoingContext(ctx, md)
		{{ if .IsUnary }}
		// Parse request
		req := &pb.{{ .InputTypeName }}{}
		{{ if .HasBody -}}
		if err := runtime.DecodeRequest(r, req); err != nil {
			runtime.WriteError(w, http.StatusBadRequest, "INVALID_ARGUMENT", err.Error())
			return
		}
		{{ end }}
		{{ if .QueryParamsTarget -}}
		if err := runtime.DecodeQueryParams(r, req, "{{ .QueryParamsTarget }}"); err != nil {
			runtime.WriteError(w, http.StatusBadRequest, "INVALID_ARGUMENT", err.Error())
			return
		}
		{{ end }}
		// Validate required fields
		{{ if .HasRequiredFields -}}
		if violations := runtime.ValidateRequired(req, []string{ {{ .RequiredFieldsList }} }); len(violations) > 0 {
			runtime.WriteValidationError(w, violations)
			return
		}
		{{ end }}
		// gRPC call with retry on transient errors
		resp, err := runtime.UnaryCallWithRetry(ctx, pool, addr,
			func(ctx context.Context, req *pb.{{ .InputTypeName }}) (*pb.{{ .OutputTypeName }}, error) {
				return client.{{ .MethodName }}(ctx, req)
			}, req)
		if err != nil {
			runtime.WriteGRPCError(w, err)
			return
		}

		runtime.WriteResponse(w, http.StatusOK, resp)
		{{ end }}
	}
}
{{ end }}
`))

type serviceFileData struct {
	ServiceName string
	ProtoImport string
	Methods     []methodData
}

type methodData struct {
	MethodName        string
	HandlerFuncName   string
	ChiMethod         string
	ChiPath           string
	PathParams        []string
	RequiredHeaders   []headerData
	InputTypeName     string
	OutputTypeName    string
	ExcludeAuth       bool
	IsUnary           bool
	HasBody           bool
	QueryParamsTarget string
	HasRequiredFields bool
	RequiredFieldsList string
}

type headerData struct {
	HeaderName string
	VarName    string
}

func generateServiceFile(svc *parser.Service, api *parser.ParsedAPI) (string, error) {
	data := serviceFileData{
		ServiceName: svc.Name,
		ProtoImport: guessProtoImport(svc),
	}

	for _, m := range svc.Methods {
		md := methodData{
			MethodName:      m.Name,
			HandlerFuncName: toLowerCamel(m.Name) + "Handler",
			ChiMethod:       chiMethodName(m.HTTPMethod),
			ChiPath:         chiPathFromProto(m.HTTPPath),
			PathParams:      m.PathParams,
			InputTypeName:   m.InputType.Name,
			OutputTypeName:  m.OutputType.Name,
			ExcludeAuth:     m.ExcludeAuth,
			IsUnary:         m.StreamType == parser.StreamUnary,
			HasBody:         m.HTTPMethod == "POST" || m.HTTPMethod == "PUT" || m.HTTPMethod == "PATCH",
			QueryParamsTarget: m.QueryParamsTarget,
		}

		for _, h := range m.RequiredHeaders {
			md.RequiredHeaders = append(md.RequiredHeaders, headerData{
				HeaderName: h,
				VarName:    "header" + toPascalCase(h),
			})
		}

		var requiredFields []string
		if m.InputType != nil {
			for _, f := range m.InputType.Fields {
				if f.Required {
					requiredFields = append(requiredFields, fmt.Sprintf("%q", f.Name))
				}
			}
		}
		if len(requiredFields) > 0 {
			md.HasRequiredFields = true
			md.RequiredFieldsList = strings.Join(requiredFields, ", ")
		}

		data.Methods = append(data.Methods, md)
	}

	var buf bytes.Buffer
	if err := serviceFileTmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func chiMethodName(httpMethod string) string {
	switch httpMethod {
	case "GET":
		return "Get"
	case "POST":
		return "Post"
	case "PUT":
		return "Put"
	case "DELETE":
		return "Delete"
	case "PATCH":
		return "Patch"
	default:
		return "HandleFunc"
	}
}

func guessProtoImport(svc *parser.Service) string {
	// Convert proto package "assistant_api.v1" → Go import path.
	// This is a heuristic – users configure via protoc flags.
	// The generated code uses the package alias "pb".
	pkg := strings.ReplaceAll(svc.ProtoPackage, ".", "/")
	return pkg
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	var result string
	for _, p := range parts {
		if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result
}
