package generator

import (
	"fmt"
	"strings"
	"text/template"

	"github.com/mrs1lentcz/protobridge/internal/parser"
)

var serviceFileTmpl = template.Must(template.New("service").Parse(`// Code generated by protoc-gen-protobridge. DO NOT EDIT.

package handler

import (
	{{ if .UsesContext }}"context"{{ end }}
	{{ if .UsesFmt }}"fmt"{{ end }}
	{{ if .UsesIO }}"io"{{ end }}
	"net/http"

	{{ if .UsesWebsocket }}"github.com/coder/websocket"{{ end }}
	"github.com/go-chi/chi/v5"
	"github.com/mrs1lentcz/gox/grpcx"
	"google.golang.org/grpc/metadata"

	"github.com/mrs1lentcz/protobridge/runtime"
	pb "{{ .ProtoImport }}"
	{{ if .UsesEmpty }}"google.golang.org/protobuf/types/known/emptypb"{{ end }}
)

func Register{{ .ServiceName }}(r chi.Router, addr string, pool *grpcx.Pool, scalingCfg grpcx.ScalingConfig, auth runtime.AuthFunc) {
	{{ range .Methods }}
	r.{{ .ChiMethod }}("{{ .ChiPath }}", {{ .HandlerFuncName }}(addr, pool, scalingCfg, auth))
	{{- end }}
}
{{ range .Methods }}
func {{ .HandlerFuncName }}(addr string, pool *grpcx.Pool, scalingCfg grpcx.ScalingConfig, auth runtime.AuthFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		// Acquire a scaled connection (auto-scales based on load).
		conn, err := pool.ConnectScaled(addr, scalingCfg)
		if err != nil {
			runtime.WriteError(w, http.StatusServiceUnavailable, "UNAVAILABLE", "connection pool exhausted")
			return
		}
		defer pool.Release(addr, conn)

		client := pb.New{{ $.ServiceName }}Client(conn)
		{{ if not .ExcludeAuth }}
		// Auth
		userData, err := auth(ctx, r)
		if err != nil {
			runtime.WriteAuthError(w, err)
			return
		}
		{{ end }}
		// Path params → metadata
		md := metadata.MD{}
		{{ range .PathParams -}}
		md.Set("{{ . }}", chi.URLParam(r, "{{ . }}"))
		{{ end }}
		// Required headers
		{{ range .RequiredHeaders -}}
		{{ .VarName }} := r.Header.Get("{{ .HeaderName }}")
		if {{ .VarName }} == "" {
			runtime.WriteError(w, http.StatusBadRequest, "INVALID_ARGUMENT", "missing required header: {{ .HeaderName }}")
			return
		}
		md.Set("{{ .HeaderName }}", {{ .VarName }})
		{{ end }}
		ctx = metadata.NewOutgoingContext(ctx, md)
		{{ if not .ExcludeAuth }}
		ctx = runtime.SetUserMetadata(ctx, userData)
		{{ end }}
		{{ if .IsUnary }}
		// Parse request
		req := &{{ .InputTypeRef }}{}
		{{ if .HasBody -}}
		if err := runtime.DecodeRequest(r, req); err != nil {
			runtime.WriteError(w, http.StatusBadRequest, "INVALID_ARGUMENT", err.Error())
			return
		}
		{{ end }}
		{{ if .QueryParamsTarget -}}
		if err := runtime.DecodeQueryParams(r, req, "{{ .QueryParamsTarget }}"); err != nil {
			runtime.WriteError(w, http.StatusBadRequest, "INVALID_ARGUMENT", err.Error())
			return
		}
		{{ end }}
		// Validate required fields
		{{ if .HasRequiredFields -}}
		if violations := runtime.ValidateRequired(req, []string{ {{ .RequiredFieldsList }} }); len(violations) > 0 {
			runtime.WriteValidationError(w, violations)
			return
		}
		{{ end }}
		// gRPC call with retry on transient errors
		resp, err := runtime.UnaryCallWithRetry(ctx, pool, addr,
			func(ctx context.Context, req *{{ .InputTypeRef }}) (*{{ .OutputTypeRef }}, error) {
				return client.{{ .MethodName }}(ctx, req)
			}, req)
		if err != nil {
			runtime.WriteGRPCError(w, err)
			return
		}

		runtime.WriteResponse(w, http.StatusOK, resp)
		{{ else if .IsSSE }}
		// SSE: server → client streaming via text/event-stream.
		stream, err := client.{{ .MethodName }}(ctx, &{{ .InputTypeRef }}{})
		if err != nil {
			runtime.WriteGRPCError(w, err)
			return
		}

		w.Header().Set("Content-Type", "text/event-stream")
		w.Header().Set("Cache-Control", "no-cache")
		w.Header().Set("Connection", "keep-alive")
		w.WriteHeader(http.StatusOK)

		flusher, ok := w.(http.Flusher)
		if !ok {
			runtime.WriteError(w, http.StatusInternalServerError, "INTERNAL", "streaming not supported")
			return
		}

		for {
			msg, err := stream.Recv()
			if err == io.EOF {
				if _, err := fmt.Fprintf(w, "event: close\ndata: {}\n\n"); err != nil {
					return
				}
				flusher.Flush()
				return
			}
			if err != nil {
				return
			}
			data, err := runtime.MarshalProto(msg)
			if err != nil {
				if _, writeErr := fmt.Fprintf(w, "event: error\ndata: {\"error\":\"marshal failure\"}\n\n"); writeErr != nil {
					return
				}
				flusher.Flush()
				return
			}
			if _, err := fmt.Fprintf(w, "data: %s\n\n", data); err != nil {
				return
			}
			flusher.Flush()
		}
		{{ else if .IsServerStream }}
		// WebSocket: server → client streaming.
		ws, err := websocket.Accept(w, r, runtime.WSAcceptOptions(runtime.WSAcceptConfig{PerRPCPatterns: {{ printf "%q" .WSOriginPatterns }}}))
		if err != nil {
			return
		}
		defer ws.CloseNow()

		stream, err := client.{{ .MethodName }}(ctx, &{{ .InputTypeRef }}{})
		if err != nil {
			ws.Close(websocket.StatusInternalError, "stream open failed")
			return
		}

		for {
			msg, err := stream.Recv()
			if err == io.EOF {
				ws.Close(websocket.StatusNormalClosure, "stream ended")
				return
			}
			if err != nil {
				ws.Close(websocket.StatusInternalError, "stream error")
				return
			}
			data, err := runtime.MarshalProto(msg)
			if err != nil {
				ws.Close(websocket.StatusInternalError, "marshal error")
				return
			}
			if err := ws.Write(ctx, websocket.MessageText, data); err != nil {
				return
			}
		}
		{{ else if .IsClientStream }}
		// WebSocket: client → server streaming.
		ws, err := websocket.Accept(w, r, runtime.WSAcceptOptions(runtime.WSAcceptConfig{PerRPCPatterns: {{ printf "%q" .WSOriginPatterns }}}))
		if err != nil {
			return
		}
		defer ws.CloseNow()

		stream, err := client.{{ .MethodName }}(ctx)
		if err != nil {
			ws.Close(websocket.StatusInternalError, "stream open failed")
			return
		}

		for {
			msgType, data, err := ws.Read(ctx)
			if err != nil {
				resp, err := stream.CloseAndRecv()
				if err != nil {
					ws.Close(websocket.StatusInternalError, "close error")
					return
				}
				result, err := runtime.MarshalProto(resp)
				if err != nil {
					ws.Close(websocket.StatusInternalError, "marshal error")
					return
				}
				if err := ws.Write(ctx, websocket.MessageText, result); err != nil {
					return
				}
				ws.Close(websocket.StatusNormalClosure, "done")
				return
			}
			msg := &{{ .InputTypeRef }}{}
			if err := runtime.UnmarshalWSFrame(msgType, data, msg); err != nil {
				ws.Close(websocket.StatusInvalidFramePayloadData, "invalid frame payload")
				return
			}
			if err := stream.Send(msg); err != nil {
				ws.Close(websocket.StatusInternalError, "send error")
				return
			}
		}
		{{ else if .IsBidiStream }}
		// WebSocket: bidirectional streaming.
		ws, err := websocket.Accept(w, r, runtime.WSAcceptOptions(runtime.WSAcceptConfig{PerRPCPatterns: {{ printf "%q" .WSOriginPatterns }}}))
		if err != nil {
			return
		}
		defer ws.CloseNow()

		stream, err := client.{{ .MethodName }}(ctx)
		if err != nil {
			ws.Close(websocket.StatusInternalError, "stream open failed")
			return
		}

		recvCtx, recvCancel := context.WithCancel(ctx)
		defer recvCancel()

		// gRPC → WS
		go func() {
			defer recvCancel()
			for {
				msg, err := stream.Recv()
				if err != nil {
					ws.Close(websocket.StatusNormalClosure, "stream ended")
					return
				}
				data, err := runtime.MarshalProto(msg)
				if err != nil {
					ws.Close(websocket.StatusInternalError, "marshal error")
					return
				}
				if err := ws.Write(recvCtx, websocket.MessageText, data); err != nil {
					return
				}
			}
		}()

		// WS → gRPC
		for {
			msgType, data, err := ws.Read(recvCtx)
			if err != nil {
				stream.CloseSend()
				return
			}
			msg := &{{ .InputTypeRef }}{}
			if err := runtime.UnmarshalWSFrame(msgType, data, msg); err != nil {
				ws.Close(websocket.StatusInvalidFramePayloadData, "invalid frame payload")
				return
			}
			if err := stream.Send(msg); err != nil {
				return
			}
		}
		{{ end }}
	}
}
{{ end }}
`))

type serviceFileData struct {
	ServiceName   string
	ProtoImport   string
	UsesEmpty     bool
	UsesContext   bool
	UsesFmt       bool
	UsesIO        bool
	UsesWebsocket bool
	Methods       []methodData
}

type methodData struct {
	MethodName        string
	HandlerFuncName   string
	ChiMethod         string
	ChiPath           string
	PathParams        []string
	RequiredHeaders   []headerData
	InputTypeName     string
	OutputTypeName    string
	InputTypeRef      string
	OutputTypeRef     string
	ExcludeAuth       bool
	IsUnary           bool
	IsServerStream    bool
	IsClientStream    bool
	IsBidiStream      bool
	IsSSE             bool
	HasBody           bool
	QueryParamsTarget string
	HasRequiredFields bool
	RequiredFieldsList string
	WSOriginPatterns  string
	WSAuth            string
}

type headerData struct {
	HeaderName string
	VarName    string
}

func generateServiceFile(svc *parser.Service, api *parser.ParsedAPI) string {
	data := serviceFileData{
		ServiceName: svc.Name,
		ProtoImport: protoImportPath(svc),
	}

	for _, m := range svc.Methods {
		// Methods carried in the parser model purely for the MCP plugin
		// (HTTPMethod is empty) must not produce REST handlers.
		if m.HTTPMethod == "" {
			continue
		}
		inRef, inEmpty := protoTypeRef(m.InputType)
		outRef, outEmpty := protoTypeRef(m.OutputType)
		if inEmpty || outEmpty {
			data.UsesEmpty = true
		}
		isStream := m.StreamType != parser.StreamUnary
		// Unary handlers wrap the call in a context.Context-typed closure
		// (UnaryCallWithRetry); the bidi branch calls context.WithCancel.
		// Other streaming branches use the ctx value but never reference
		// the context.Context type.
		if !isStream || m.StreamType == parser.StreamBidi {
			data.UsesContext = true
		}
		if m.SSE {
			data.UsesFmt = true
			data.UsesIO = true
		} else if isStream {
			data.UsesWebsocket = true
			if m.StreamType == parser.StreamServer {
				data.UsesIO = true
			}
		}
		md := methodData{
			MethodName:      m.Name,
			HandlerFuncName: toLowerCamel(m.Name) + "Handler",
			ChiMethod:       chiMethodName(m.HTTPMethod),
			ChiPath:         chiPathFromProto(m.HTTPPath),
			PathParams:      m.PathParams,
			InputTypeName:   m.InputType.Name,
			OutputTypeName:  m.OutputType.Name,
			InputTypeRef:    inRef,
			OutputTypeRef:   outRef,
			ExcludeAuth:     m.ExcludeAuth,
			IsUnary:         m.StreamType == parser.StreamUnary,
			IsServerStream:  m.StreamType == parser.StreamServer,
			IsClientStream:  m.StreamType == parser.StreamClient,
			IsBidiStream:    m.StreamType == parser.StreamBidi,
			IsSSE:           m.SSE,
			HasBody:         m.HTTPMethod == "POST" || m.HTTPMethod == "PUT" || m.HTTPMethod == "PATCH",
			QueryParamsTarget: m.QueryParamsTarget,
			WSOriginPatterns:  m.WSOriginPatterns,
			WSAuth:            m.WSAuth,
		}

		for _, h := range m.RequiredHeaders {
			md.RequiredHeaders = append(md.RequiredHeaders, headerData{
				HeaderName: h,
				VarName:    "header" + toPascalCase(h),
			})
		}

		var requiredFields []string
		if m.InputType != nil {
			for _, f := range m.InputType.Fields {
				if f.Required {
					requiredFields = append(requiredFields, fmt.Sprintf("%q", f.Name))
				}
			}
		}
		if len(requiredFields) > 0 {
			md.HasRequiredFields = true
			md.RequiredFieldsList = strings.Join(requiredFields, ", ")
		}

		data.Methods = append(data.Methods, md)
	}

	// Conditional imports leave blank lines / empty groups — gofmt the
	// output so the emitted file is byte-stable and integrators don't need
	// to run goimports after every protoc invocation. Failures here are
	// generator bugs, not input bugs, so renderTemplate panics instead of
	// silently surfacing an unreachable error.
	return renderTemplate(serviceFileTmpl, data)
}

func chiMethodName(httpMethod string) string {
	switch httpMethod {
	case "GET":
		return "Get"
	case "POST":
		return "Post"
	case "PUT":
		return "Put"
	case "DELETE":
		return "Delete"
	case "PATCH":
		return "Patch"
	default:
		return "HandleFunc"
	}
}

// protoImportPath returns the Go import path for a service's proto package.
// Uses go_package from the proto file when available, falls back to
// converting the proto package name.
func protoImportPath(svc *parser.Service) string {
	if svc.GoPackage != "" {
		return svc.GoPackage
	}
	// Fallback: convert proto package "assistant_api.v1" → "assistant_api/v1".
	return strings.ReplaceAll(svc.ProtoPackage, ".", "/")
}

// protoTypeRef returns the qualified Go type name for a proto message and
// whether the type is google.protobuf.Empty (in which case emptypb must be
// imported).
func protoTypeRef(mt *parser.MessageType) (ref string, isEmpty bool) {
	if mt.FullName == ".google.protobuf.Empty" || mt.FullName == "google.protobuf.Empty" {
		return "emptypb.Empty", true
	}
	return "pb." + mt.Name, false
}

func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-'
	})
	var result string
	for _, p := range parts {
		if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result
}
