package generator

import (
	"sort"
	"strings"
	"text/template"

	"github.com/mrs1lentcz/protobridge/internal/parser"
)

var mainTmpl = template.Must(template.New("main").Parse(`// Code generated by protoc-gen-protobridge. DO NOT EDIT.

package main

import (
	"context"
	"crypto/tls"
	"log"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/mrs1lentcz/gox/errorx"
	"github.com/mrs1lentcz/gox/grpcx"
	"github.com/mrs1lentcz/gox/sentryx"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/credentials/insecure"
	{{ if .HasAuth }}"google.golang.org/protobuf/proto"{{ end }}

	"github.com/mrs1lentcz/protobridge/runtime"
	{{ if or .HasBroadcasts .HasWSAuth }}"github.com/mrs1lentcz/protobridge/runtime/events"{{ end }}
	{{ if .HasBroadcasts }}eventspb "{{ .EventsPkg }}"{{ end }}
	"{{ .HandlerPkg }}"
	{{ if .HasAuth }}{{ .AuthPkgAlias }} "{{ .AuthProtoImport }}"{{ end }}
)

func main() {
	// Validate WS-related env combinations at startup so misconfiguration
	// surfaces before any traffic hits the gateway rather than on the
	// first WS upgrade.
	runtime.InitWSConfig()

	// OpenTelemetry (tracing + metrics)
	serviceName := os.Getenv("PROTOBRIDGE_OTEL_SERVICE_NAME")
	if serviceName == "" {
		serviceName = "protobridge"
	}
	otelShutdown, err := runtime.InitOTel(context.Background(), runtime.OTelConfig{
		ServiceName:  serviceName,
		OTLPEndpoint: os.Getenv("PROTOBRIDGE_OTEL_ENDPOINT"),
	})
	if err != nil {
		log.Fatalf("otel init: %v", err)
	}
	defer runtime.GracefulShutdownOTel(otelShutdown)

	// Sentry
	dsn := os.Getenv("PROTOBRIDGE_SENTRY_DSN")
	if err := sentryx.Init(sentryx.DefaultClientOptions(dsn, "protobridge")); err != nil {
		log.Fatalf("sentry init: %v", err)
	}
	defer sentryx.Flush(2 * time.Second)

	// Error reporter
	if dsn != "" {
		errorx.MustInit("sentry:" + dsn)
	} else {
		errorx.MustInit("stderr")
	}
	defer errorx.CloseReporter()

	// Validate required environment variables
	{{ range .Services -}}
	{{ .EnvAddr }} := runtime.PreferIPFamily(requireEnv("{{ .EnvAddrKey }}"))
	{{ end }}
	{{ range .BroadcastServices -}}
	{{ .EnvAddr }} := runtime.PreferIPFamily(requireEnv("{{ .EnvAddrKey }}"))
	{{ end }}

	// gRPC connection pool with adaptive scaling and health monitoring.
	// Each service scales from 1 to MaxConns connections based on load.
	// Default: 100 concurrent streams per connection, max 10 connections.
	pool := grpcx.NewPool()
	pool.EnableHealthWatch(30 * time.Second)
	defer pool.Close()

	scalingCfg := grpcx.ScalingConfig{
		StreamsPerConn: 100,
		MaxConns:       10,
	}

	// Pre-create first connection per service (fail-fast on bad addresses).
	{{ range .Services }}
	if _, err := pool.ConnectScaled({{ .EnvAddr }}, scalingCfg, dialOpts("{{ .EnvTLSKey }}", "{{ .EnvGRPCOptsKey }}")...); err != nil {
		log.Fatalf("connecting to %s: %v", {{ .EnvAddr }}, err)
	}
	{{ end }}

	{{ if .HasAuth -}}
	// Auth function: calls {{ .AuthServiceName }}.{{ .AuthMethodName }} on every request.
	authFn := runtime.AuthFunc(func(ctx context.Context, r *http.Request) ([]byte, error) {
		conn, err := pool.ConnectScaled({{ .AuthAddrVar }}, scalingCfg)
		if err != nil {
			return nil, err
		}
		defer pool.Release({{ .AuthAddrVar }}, conn)

		client := {{ .AuthPkgAlias }}.New{{ .AuthServiceName }}Client(conn)

		headers := make(map[string]string)
		for k, v := range r.Header {
			if len(v) > 0 {
				headers[k] = v[0]
			}
		}

		resp, err := client.{{ .AuthMethodName }}(ctx, &{{ .AuthPkgAlias }}.{{ .AuthInputType }}{Headers: headers})
		if err != nil {
			return nil, err
		}

		return proto.Marshal(resp)
	})
	{{ else -}}
	authFn := runtime.NoAuth()
	{{ end }}

	// Router
	r := chi.NewRouter()
	r.Use(runtime.CORSMiddleware(runtime.CORSConfigFromEnv()))
	r.Use(runtime.OTelMiddleware(serviceName))
	r.Use(runtime.SentryMiddleware())

	// Proxy health endpoint (always available, independent of backend services)
	r.Get("/healthz", runtime.HealthHandler())

	{{ if .HasWSAuth -}}
	// WebSocket ticket flow: browser new WebSocket() can't set Authorization,
	// so FE POSTs to the issuer with its normal auth header, gets a ticket,
	// and appends ?ticket=<t> to the ws:// URL. NewWSAuth below replays the
	// stored header into a cloned request on redeem so the upstream AuthFunc
	// sees the same shape it would for a header upgrade. Independent of the
	// broadcast ticket subsystem — its labels (Authorization header) differ
	// from broadcast labels (principal metadata).
	wsTicketPath := os.Getenv("PROTOBRIDGE_WS_TICKET_PATH")
	if wsTicketPath == "" {
		wsTicketPath = "/api/ws/ticket"
	}
	wsTicketStore := events.MountIssuer(r, wsTicketPath, runtime.WSAuthTicketPrincipal)
	defer wsTicketStore.Close()
	{{ range .Services -}}
	{{ if .HasWSAuth -}}
	{{ .ServiceAuthFnVar }} := runtime.NewWSAuth(runtime.WSAuthConfig{
		Inner:       authFn,
		TicketStore: wsTicketStore,
		Modes:       []string{ {{ range $i, $m := .WSAuthModes }}{{ if $i }}, {{ end }}{{ printf "%q" $m }}{{ end }} },
	})
	{{ end -}}
	{{ end }}
	{{ end }}

	{{ range .Services -}}
	{{ if .HasREST -}}
	handler.Register{{ .ServiceName }}(r, {{ .EnvAddr }}, pool, scalingCfg, {{ if .HasWSAuth }}{{ .ServiceAuthFnVar }}{{ else }}authFn{{ end }})
	{{ end -}}
	{{ end }}

	{{ if .HasBroadcasts -}}
	// Broadcast services: open one long-lived gRPC stream per service and
	// fan it out across every connected WS client. The connection lives for
	// the gateway process's lifetime — separate from the per-request pool
	// (which assumes short-lived borrows).
	broadcastCtx, broadcastCancel := context.WithCancel(context.Background())
	defer broadcastCancel()

	{{ if and .HasAuth .AuthHasLabels -}}
	// Auth response declares a labels map — extract per request and feed
	// into BroadcastConfig.PrincipalLabels so the hub filters events to the
	// authenticated user's label set.
	principalLabelsFn := func(r *http.Request) (map[string]string, error) {
		conn, err := pool.ConnectScaled({{ .AuthAddrVar }}, scalingCfg)
		if err != nil {
			return nil, err
		}
		defer pool.Release({{ .AuthAddrVar }}, conn)
		client := {{ .AuthPkgAlias }}.New{{ .AuthServiceName }}Client(conn)
		headers := make(map[string]string)
		for k, v := range r.Header {
			if len(v) > 0 {
				headers[k] = v[0]
			}
		}
		resp, err := client.{{ .AuthMethodName }}(r.Context(), &{{ .AuthPkgAlias }}.{{ .AuthInputType }}{Headers: headers})
		if err != nil {
			return nil, err
		}
		return resp.GetLabels(), nil
	}

	// Ticket store: browsers' EventSource can't send Authorization headers,
	// so a short-lived one-shot ticket bridges the gap. FE POSTs to the
	// issuer endpoint with its normal auth credentials, then opens the
	// SSE stream with ?ticket=<t>. In-memory store is fine for single-
	// replica gateways; swap for a shared backend (Redis, DB) when scaling
	// issuer and hub across pods.
	broadcastTicketPath := os.Getenv("PROTOBRIDGE_EVENTS_TICKET_PATH")
	if broadcastTicketPath == "" {
		broadcastTicketPath = "/api/events/ticket"
	}
	broadcastTicketStore := events.MountIssuer(r, broadcastTicketPath, principalLabelsFn)
	defer broadcastTicketStore.Close()
	{{ else -}}
	var principalLabelsFn func(*http.Request) (map[string]string, error)
	var broadcastTicketStore events.TicketStore
	{{ end }}
	{{ range .BroadcastServices }}
	{{ .ConnVar }}, err := grpc.NewClient({{ .EnvAddr }}, dialOpts({{ printf "%q" .EnvTLSKey }}, {{ printf "%q" .EnvGRPCOptsKey }})...)
	if err != nil {
		log.Fatalf("dial broadcast %s: %v", {{ printf "%q" .EnvAddrKey }}, err)
	}
	defer func() { _ = {{ .ConnVar }}.Close() }()
	eventspb.Register{{ .ServiceName }}Broadcast(broadcastCtx, r, {{ .ConnVar }}, {{ printf "%q" .Route }}, events.BroadcastConfig{
		PrincipalLabels: principalLabelsFn,
		TicketStore:     broadcastTicketStore,
	})
	{{ end }}
	{{ end }}

	// Prometheus metrics endpoint
	metricsPort := os.Getenv("PROTOBRIDGE_METRICS_PORT")
	if metricsPort != "" {
		go func() {
			mux := http.NewServeMux()
			mux.Handle("/metrics", promhttp.Handler())
			log.Printf("prometheus metrics on :%s/metrics", metricsPort)
			if err := http.ListenAndServe(":"+metricsPort, mux); err != nil {
				log.Printf("metrics server error: %v", err)
			}
		}()
	}

	// HTTP server
	port := os.Getenv("PROTOBRIDGE_PORT")
	if port == "" {
		port = "8080"
	}

	srv := &http.Server{
		Addr:              ":" + port,
		Handler:           r,
		ReadHeaderTimeout: envDuration("PROTOBRIDGE_READ_HEADER_TIMEOUT", 10*time.Second),
		ReadTimeout:       envDuration("PROTOBRIDGE_READ_TIMEOUT", 30*time.Second),
		// WriteTimeout is 0 by default to support long-lived WebSocket/SSE
		// connections. Set PROTOBRIDGE_WRITE_TIMEOUT to enforce a limit for
		// unary-only deployments.
		WriteTimeout:   envDuration("PROTOBRIDGE_WRITE_TIMEOUT", 0),
		IdleTimeout:    envDuration("PROTOBRIDGE_IDLE_TIMEOUT", 120*time.Second),
		MaxHeaderBytes: envInt("PROTOBRIDGE_MAX_HEADER_BYTES", 1<<20), // 1 MiB
	}

	// TLS configuration
	tlsCert := os.Getenv("PROTOBRIDGE_TLS_CERT")
	tlsKey := os.Getenv("PROTOBRIDGE_TLS_KEY")
	tlsServerName := os.Getenv("PROTOBRIDGE_TLS_SERVER_NAME")
	useTLS := tlsCert != "" && tlsKey != ""

	if useTLS {
		tlsCfg := &tls.Config{
			MinVersion: tls.VersionTLS12,
		}
		if tlsServerName != "" {
			tlsCfg.ServerName = tlsServerName
		}
		srv.TLSConfig = tlsCfg
	}

	// Graceful shutdown
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	go func() {
		if useTLS {
			log.Printf("protobridge listening on :%s (TLS)", port)
			err = srv.ListenAndServeTLS(tlsCert, tlsKey)
		} else {
			log.Printf("protobridge listening on :%s", port)
			err = srv.ListenAndServe()
		}
		if err != nil && err != http.ErrServerClosed {
			log.Fatalf("server error: %v", err)
		}
	}()

	<-ctx.Done()
	log.Println("shutting down...")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Printf("shutdown error: %v", err)
	}
}

func requireEnv(key string) string {
	val := os.Getenv(key)
	if val == "" {
		log.Fatalf("required environment variable %s is not set", key)
	}
	return val
}

func envDuration(key string, def time.Duration) time.Duration {
	val := os.Getenv(key)
	if val == "" {
		return def
	}
	d, err := time.ParseDuration(val)
	if err != nil {
		log.Fatalf("%s: invalid duration %q: %v", key, val, err)
	}
	return d
}

func envInt(key string, def int) int {
	val := os.Getenv(key)
	if val == "" {
		return def
	}
	n, err := strconv.Atoi(val)
	if err != nil {
		log.Fatalf("%s: invalid integer %q: %v", key, val, err)
	}
	return n
}

func dialOpts(tlsEnvKey, grpcOptsEnvKey string) []grpc.DialOption {
	opts := []grpc.DialOption{
		grpc.WithStatsHandler(otelgrpc.NewClientHandler()),
	}
	if os.Getenv(tlsEnvKey) == "true" {
		opts = append(opts, grpc.WithTransportCredentials(credentials.NewTLS(nil)))
	} else {
		opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
	}

	// Global gRPC options
	if globalOpts := os.Getenv("PROTOBRIDGE_GRPC_OPTIONS"); globalOpts != "" {
		parsed, err := runtime.ParseGRPCOptions(globalOpts)
		if err != nil {
			log.Fatalf("PROTOBRIDGE_GRPC_OPTIONS: %v", err)
		}
		opts = append(opts, parsed...)
	}

	// Per-service gRPC options override
	if serviceOpts := os.Getenv(grpcOptsEnvKey); serviceOpts != "" {
		parsed, err := runtime.ParseGRPCOptions(serviceOpts)
		if err != nil {
			log.Fatalf("%s: %v", grpcOptsEnvKey, err)
		}
		opts = append(opts, parsed...)
	}

	return opts
}
`))

type mainData struct {
	Services        []mainServiceData
	HandlerPkg      string // Go import path of the generated handler subpackage
	HasAuth         bool
	AuthConnVar     string
	AuthAddrVar     string // e.g. "authServiceAddr"
	AuthServiceName string // e.g. "AuthService"
	AuthMethodName  string // e.g. "Authenticate"
	AuthPkgAlias    string // e.g. "authServicepb"
	AuthProtoImport string // Go import path of the auth service's proto package
	AuthInputType   string // e.g. "AuthRequest"
	AuthHasLabels   bool   // AuthResponse has a `labels` field — enables per-principal filtering

	// Broadcast WS endpoints generated from (protobridge.broadcast) services.
	// Empty when no broadcast service is declared; main.go then omits the
	// events-runtime import and bus initialisation.
	HasBroadcasts     bool
	EventsPkg         string // import path of the events plugin output
	BroadcastServices []mainBroadcastData

	// HasWSAuth is true when at least one streaming method somewhere in
	// Services carries (protobridge.ws_auth). Drives the WS ticket issuer
	// mount and the per-service NewWSAuth wrap.
	HasWSAuth bool
}

type mainBroadcastData struct {
	ServiceName    string // source service name, e.g. "OrderBroadcast" — generated symbol is Register<ServiceName>Broadcast
	Route          string // HTTP path
	ConnVar        string // long-lived dial conn variable, e.g. "v1BroadcastConn"
	EnvAddr        string // address env-var name, e.g. "v1BroadcastAddr"
	EnvAddrKey     string // env key, e.g. "PROTOBRIDGE_V1_BROADCAST_ADDR"
	EnvTLSKey      string // env key, e.g. "PROTOBRIDGE_V1_BROADCAST_TLS"
	EnvGRPCOptsKey string // env key, e.g. "PROTOBRIDGE_V1_BROADCAST_GRPC_OPTIONS"
}

// collectWSAuthModes returns the sorted, de-duplicated union of
// (protobridge.ws_auth) tokens across every method of svc. Empty when
// no method declares the option — the caller treats that as "no WS
// auth wrap needed". The per-service union is what the generated
// NewWSAuth wrap accepts, since handler.Register… takes a single
// AuthFunc for the whole service; a method declaring only "header"
// coexists with the wrap because NewWSAuth short-circuits to Inner
// when an Authorization header is present.
func collectWSAuthModes(svc *parser.Service) []string {
	seen := map[string]struct{}{}
	for _, m := range svc.Methods {
		if m.WSAuth == "" {
			continue
		}
		for _, tok := range strings.Split(m.WSAuth, ",") {
			tok = strings.TrimSpace(tok)
			if tok == "" {
				continue
			}
			seen[tok] = struct{}{}
		}
	}
	if len(seen) == 0 {
		return nil
	}
	// Fixed order so template output is stable: header before ticket,
	// unknown tokens (if any ever slip past the parser) trail
	// alphabetically so the generator output remains deterministic and
	// diff-friendly.
	ordered := make([]string, 0, len(seen))
	for _, pref := range []string{"header", "ticket"} {
		if _, ok := seen[pref]; ok {
			ordered = append(ordered, pref)
			delete(seen, pref)
		}
	}
	rest := make([]string, 0, len(seen))
	for k := range seen {
		rest = append(rest, k)
	}
	sort.Strings(rest)
	ordered = append(ordered, rest...)
	return ordered
}

// hasLabelsMapField returns true when the AuthResponse declares
// `map<string, string> labels = N;`. The proto3 map encoding is a
// TYPE_MESSAGE repeated field whose TypeName ends with ".LabelsEntry",
// so we check all three facets to avoid false positives on a scalar
// field that happens to be named `labels`.
func hasLabelsMapField(mt *parser.MessageType) bool {
	if mt == nil {
		return false
	}
	for _, f := range mt.Fields {
		if f.Name != "labels" {
			continue
		}
		if !f.Repeated {
			continue
		}
		if !strings.HasSuffix(f.TypeName, ".LabelsEntry") {
			continue
		}
		return true
	}
	return false
}

type mainServiceData struct {
	ServiceName    string
	PkgAlias       string
	ProtoImport    string
	EnvAddr        string // variable name, e.g. "voiceChatServiceAddr"
	EnvAddrKey     string // env key, e.g. "PROTOBRIDGE_VOICE_CHAT_SERVICE_ADDR"
	EnvTLSKey      string // env key, e.g. "PROTOBRIDGE_VOICE_CHAT_SERVICE_TLS"
	EnvGRPCOptsKey string // env key, e.g. "PROTOBRIDGE_VOICE_CHAT_SERVICE_GRPC_OPTIONS"
	ConnVar        string // variable name, e.g. "voiceChatServiceConn"
	// HasREST is false for synthetic auth-only services that need a gRPC
	// connection (for the auth function) but have no generated register*
	// function. The main template skips register* for these.
	HasREST bool

	// HasWSAuth is true when at least one method on this service declares
	// (protobridge.ws_auth). When set, the generated main wraps authFn in
	// runtime.NewWSAuth and passes ServiceAuthFnVar to handler.Register…
	// instead of the raw authFn. Scope is per-service because
	// handler.Register… takes one AuthFunc for the whole service.
	HasWSAuth        bool
	WSAuthModes      []string // union of ws_auth tokens across this service's methods, e.g. ["header","ticket"]
	ServiceAuthFnVar string   // variable name holding the wrapped AuthFunc, e.g. "voiceChatServiceAuthFn"
}

func generateMain(api *parser.ParsedAPI, handlerPkg, eventsPkg string) string {
	data := mainData{HandlerPkg: handlerPkg, EventsPkg: eventsPkg}

	for _, bs := range api.BroadcastServices {
		screaming := toScreamingSnake(bs.Name)
		data.BroadcastServices = append(data.BroadcastServices, mainBroadcastData{
			ServiceName:    bs.Name,
			Route:          bs.Route,
			ConnVar:        toLowerCamel(bs.Name) + "Conn",
			EnvAddr:        toLowerCamel(bs.Name) + "Addr",
			EnvAddrKey:     "PROTOBRIDGE_" + screaming + "_ADDR",
			EnvTLSKey:      "PROTOBRIDGE_" + screaming + "_TLS",
			EnvGRPCOptsKey: "PROTOBRIDGE_" + screaming + "_GRPC_OPTIONS",
		})
	}
	data.HasBroadcasts = len(data.BroadcastServices) > 0

	for _, svc := range api.Services {
		screaming := toScreamingSnake(svc.Name)
		sd := mainServiceData{
			ServiceName: svc.Name,
			PkgAlias:    toLowerCamel(svc.Name) + "pb",
			ProtoImport: protoImportPath(svc),
			EnvAddr:     toLowerCamel(svc.Name) + "Addr",
			EnvAddrKey:  "PROTOBRIDGE_" + screaming + "_ADDR",
			EnvTLSKey:      "PROTOBRIDGE_" + screaming + "_TLS",
			EnvGRPCOptsKey: "PROTOBRIDGE_" + screaming + "_GRPC_OPTIONS",
			ConnVar:        toLowerCamel(svc.Name) + "Conn",
			HasREST:        true,
		}
		sd.WSAuthModes = collectWSAuthModes(svc)
		if len(sd.WSAuthModes) > 0 {
			sd.HasWSAuth = true
			sd.ServiceAuthFnVar = toLowerCamel(svc.Name) + "AuthFn"
			data.HasWSAuth = true
		}
		data.Services = append(data.Services, sd)
	}

	if api.AuthMethod != nil {
		data.HasAuth = true
		data.AuthHasLabels = hasLabelsMapField(api.AuthMethod.OutputType)
		data.AuthServiceName = api.AuthMethod.ServiceName
		data.AuthMethodName = api.AuthMethod.MethodName
		data.AuthInputType = api.AuthMethod.InputType.Name
		data.AuthPkgAlias = toLowerCamel(api.AuthMethod.ServiceName) + "pb"
		data.AuthAddrVar = toLowerCamel(api.AuthMethod.ServiceName) + "Addr"
		data.AuthProtoImport = api.AuthMethod.GoPackage

		// Find the service data for the auth service.
		for _, sd := range data.Services {
			if sd.ServiceName == api.AuthMethod.ServiceName {
				data.AuthConnVar = sd.ConnVar
				data.AuthAddrVar = sd.EnvAddr
				data.AuthPkgAlias = sd.PkgAlias
				data.AuthProtoImport = sd.ProtoImport
				break
			}
		}
		// Auth service might not have REST endpoints but still needs a connection.
		if data.AuthConnVar == "" {
			screaming := toScreamingSnake(api.AuthMethod.ServiceName)
			connVar := toLowerCamel(api.AuthMethod.ServiceName) + "Conn"
			data.AuthConnVar = connVar
			data.Services = append(data.Services, mainServiceData{
				ServiceName:    api.AuthMethod.ServiceName,
				PkgAlias:       toLowerCamel(api.AuthMethod.ServiceName) + "pb",
				ProtoImport:    api.AuthMethod.GoPackage,
				EnvAddr:        toLowerCamel(api.AuthMethod.ServiceName) + "Addr",
				EnvAddrKey:     "PROTOBRIDGE_" + screaming + "_ADDR",
				EnvTLSKey:      "PROTOBRIDGE_" + screaming + "_TLS",
				EnvGRPCOptsKey: "PROTOBRIDGE_" + screaming + "_GRPC_OPTIONS",
				ConnVar:        connVar,
			})
		}
	}

	return renderTemplate(mainTmpl, data)
}
