package generator

import (
	"bytes"
	"text/template"

	"github.com/mrs1lentcz/protobridge/internal/parser"
)

var mainTmpl = template.Must(template.New("main").Parse(`// Code generated by protoc-gen-protobridge. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/mrs1lentcz/gox/errorx"
	"github.com/mrs1lentcz/gox/grpcx"
	"github.com/mrs1lentcz/gox/sentryx"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/credentials/insecure"

	"github.com/mrs1lentcz/protobridge/runtime"
	{{ range .Services -}}
	{{ .PkgAlias }} "{{ .ProtoImport }}"
	{{ end }}
)

func main() {
	// OpenTelemetry (tracing + metrics)
	serviceName := os.Getenv("PROTOBRIDGE_OTEL_SERVICE_NAME")
	if serviceName == "" {
		serviceName = "protobridge"
	}
	otelShutdown, err := runtime.InitOTel(context.Background(), runtime.OTelConfig{
		ServiceName:  serviceName,
		OTLPEndpoint: os.Getenv("PROTOBRIDGE_OTEL_ENDPOINT"),
	})
	if err != nil {
		log.Fatalf("otel init: %v", err)
	}
	defer runtime.GracefulShutdownOTel(otelShutdown)

	// Sentry
	dsn := os.Getenv("PROTOBRIDGE_SENTRY_DSN")
	if err := sentryx.Init(sentryx.DefaultClientOptions(dsn, "protobridge")); err != nil {
		log.Fatalf("sentry init: %v", err)
	}
	defer sentryx.Flush(2 * time.Second)

	// Error reporter
	if dsn != "" {
		errorx.MustInit("sentry:" + dsn)
	} else {
		errorx.MustInit("stderr")
	}
	defer errorx.CloseReporter()

	// Validate required environment variables
	{{ range .Services -}}
	{{ .EnvAddr }} := requireEnv("{{ .EnvAddrKey }}")
	{{ end }}

	// gRPC connection pool with health monitoring
	pool := grpcx.NewPool()
	pool.EnableHealthWatch(30 * time.Second)
	defer pool.Close()

	{{ range .Services }}
	{{ .ConnVar }}, err := pool.Connect({{ .EnvAddr }}, dialOpts("{{ .EnvTLSKey }}")...)
	if err != nil {
		log.Fatalf("connecting to %s: %v", {{ .EnvAddr }}, err)
	}
	{{ end }}

	{{ if .HasAuth -}}
	// Auth function
	authFn := runtime.NewAuthFunc({{ .AuthConnVar }})
	{{ else -}}
	authFn := runtime.NoAuth()
	{{ end }}

	// Router
	r := chi.NewRouter()
	r.Use(runtime.OTelMiddleware(serviceName))
	r.Use(runtime.SentryMiddleware())

	{{ range .Services -}}
	register{{ .ServiceName }}(r, {{ .ConnVar }}, "{{ .EnvAddrKey }}", pool, authFn)
	{{ end }}

	// Prometheus metrics endpoint
	metricsPort := os.Getenv("PROTOBRIDGE_METRICS_PORT")
	if metricsPort != "" {
		go func() {
			mux := http.NewServeMux()
			mux.Handle("/metrics", promhttp.Handler())
			log.Printf("prometheus metrics on :%s/metrics", metricsPort)
			if err := http.ListenAndServe(":"+metricsPort, mux); err != nil {
				log.Printf("metrics server error: %v", err)
			}
		}()
	}

	// HTTP server
	port := os.Getenv("PROTOBRIDGE_PORT")
	if port == "" {
		port = "8080"
	}

	srv := &http.Server{
		Addr:    ":" + port,
		Handler: r,
	}

	// Graceful shutdown
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	go func() {
		cert := os.Getenv("PROTOBRIDGE_TLS_CERT")
		key := os.Getenv("PROTOBRIDGE_TLS_KEY")

		log.Printf("protobridge listening on :%s", port)
		var err error
		if cert != "" && key != "" {
			err = srv.ListenAndServeTLS(cert, key)
		} else {
			err = srv.ListenAndServe()
		}
		if err != nil && err != http.ErrServerClosed {
			log.Fatalf("server error: %v", err)
		}
	}()

	<-ctx.Done()
	log.Println("shutting down...")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Printf("shutdown error: %v", err)
	}
}

func requireEnv(key string) string {
	val := os.Getenv(key)
	if val == "" {
		log.Fatalf("required environment variable %s is not set", key)
	}
	return val
}

func dialOpts(tlsEnvKey string) []grpc.DialOption {
	opts := []grpc.DialOption{
		grpc.WithStatsHandler(otelgrpc.NewClientHandler()),
	}
	if os.Getenv(tlsEnvKey) == "true" {
		opts = append(opts, grpc.WithTransportCredentials(credentials.NewTLS(nil)))
	} else {
		opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
	}
	return opts
}
`))

type mainData struct {
	Services    []mainServiceData
	HasAuth     bool
	AuthConnVar string
}

type mainServiceData struct {
	ServiceName string
	PkgAlias    string
	ProtoImport string
	EnvAddr     string // variable name, e.g. "voiceChatServiceAddr"
	EnvAddrKey  string // env key, e.g. "PROTOBRIDGE_VOICE_CHAT_SERVICE_ADDR"
	EnvTLSKey   string // env key, e.g. "PROTOBRIDGE_VOICE_CHAT_SERVICE_TLS"
	ConnVar     string // variable name, e.g. "voiceChatServiceConn"
}

func generateMain(api *parser.ParsedAPI) (string, error) {
	data := mainData{}

	for _, svc := range api.Services {
		screaming := toScreamingSnake(svc.Name)
		sd := mainServiceData{
			ServiceName: svc.Name,
			PkgAlias:    toLowerCamel(svc.Name) + "pb",
			ProtoImport: guessProtoImport(svc),
			EnvAddr:     toLowerCamel(svc.Name) + "Addr",
			EnvAddrKey:  "PROTOBRIDGE_" + screaming + "_ADDR",
			EnvTLSKey:   "PROTOBRIDGE_" + screaming + "_TLS",
			ConnVar:     toLowerCamel(svc.Name) + "Conn",
		}
		data.Services = append(data.Services, sd)
	}

	if api.AuthMethod != nil {
		data.HasAuth = true
		// Find the connection variable for the auth service.
		for _, sd := range data.Services {
			if sd.ServiceName == api.AuthMethod.ServiceName {
				data.AuthConnVar = sd.ConnVar
				break
			}
		}
		// Auth service might not have REST endpoints but still needs a connection.
		if data.AuthConnVar == "" {
			screaming := toScreamingSnake(api.AuthMethod.ServiceName)
			connVar := toLowerCamel(api.AuthMethod.ServiceName) + "Conn"
			data.AuthConnVar = connVar
			data.Services = append(data.Services, mainServiceData{
				ServiceName: api.AuthMethod.ServiceName,
				PkgAlias:    toLowerCamel(api.AuthMethod.ServiceName) + "pb",
				ProtoImport: api.AuthMethod.ServiceName, // placeholder
				EnvAddr:     toLowerCamel(api.AuthMethod.ServiceName) + "Addr",
				EnvAddrKey:  "PROTOBRIDGE_" + screaming + "_ADDR",
				EnvTLSKey:   "PROTOBRIDGE_" + screaming + "_TLS",
				ConnVar:     connVar,
			})
		}
	}

	var buf bytes.Buffer
	if err := mainTmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
