package mcpgen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"

	"github.com/mrs1lentcz/protobridge/internal/parser"
)

// generateHandlerFile renders one handler file per gRPC service. The file
// declares an Add<Service>ToServer(srv *mcp.Server, addr string, pool *grpcx.Pool, scalingCfg grpcx.ScalingConfig)
// function that registers every MCP-enabled method as an mcp.Tool with a
// JSON Schema input and a closure that performs the gRPC call.
func generateHandlerFile(svc *parser.Service) (string, error) {
	tools := []toolData{}
	for _, m := range svc.Methods {
		if !m.MCP {
			continue
		}
		// Stream methods can't be exposed as MCP tools (tools are unary).
		if m.StreamType != parser.StreamUnary {
			continue
		}
		t := toolData{
			MethodName:    m.Name,
			ToolName:      toSnakeCase(m.Name),
			Description:   buildDescription(m),
			InputSchema:   jsonSchemaForInput(m.InputType),
			InputTypeRef:  protoTypeRef(m.InputType),
			OutputTypeRef: protoTypeRef(m.OutputType),
		}
		tools = append(tools, t)
	}

	data := handlerFileData{
		ServiceName: svc.Name,
		ProtoImport: protoImportPath(svc),
		Tools:       tools,
		UsesEmpty:   anyEmpty(svc),
	}

	var buf bytes.Buffer
	if err := handlerTmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("gofmt mcp handler: %w\n%s", err, buf.String())
	}
	return string(formatted), nil
}

type handlerFileData struct {
	ServiceName string
	ProtoImport string
	UsesEmpty   bool
	Tools       []toolData
}

type toolData struct {
	MethodName    string
	ToolName      string
	Description   string
	InputSchema   string // raw JSON
	InputTypeRef  string // pb.Foo or emptypb.Empty
	OutputTypeRef string
}

var handlerTmpl = template.Must(template.New("mcp_handler").Parse(`// Code generated by protoc-gen-mcp. DO NOT EDIT.

package handler

import (
	"context"
	"encoding/json"

	mcpsdk "github.com/mark3labs/mcp-go/mcp"
	mcpserver "github.com/mark3labs/mcp-go/server"
	"github.com/mrs1lentcz/gox/grpcx"

	"github.com/mrs1lentcz/protobridge/runtime/mcp"
	pb "{{ .ProtoImport }}"
	{{ if .UsesEmpty }}"google.golang.org/protobuf/types/known/emptypb"{{ end }}
)

// Add{{ .ServiceName }}ToServer registers every MCP-enabled method of
// {{ .ServiceName }} as an mcp.Tool against srv.
func Add{{ .ServiceName }}ToServer(srv *mcp.Server, addr string, pool *grpcx.Pool, scalingCfg grpcx.ScalingConfig) {
{{ range .Tools }}
	srv.AddTool(
		{{ printf "%q" .ToolName }},
		{{ printf "%q" .Description }},
		json.RawMessage({{ printf "%q" .InputSchema }}),
		func(ctx context.Context, req mcpsdk.CallToolRequest) (*mcpsdk.CallToolResult, error) {
			conn, err := pool.ConnectScaled(addr, scalingCfg)
			if err != nil {
				return nil, err
			}
			defer pool.Release(addr, conn)
			client := pb.New{{ $.ServiceName }}Client(conn)
			in := &{{ .InputTypeRef }}{}
			out := &{{ .OutputTypeRef }}{}
			return srv.CallUnary(ctx, req, in, out, func(ctx context.Context) error {
				resp, err := client.{{ .MethodName }}(ctx, in)
				if err != nil {
					return err
				}
				*out = *resp
				return nil
			})
		},
	)
{{ end }}
	_ = mcpserver.ToolHandlerFunc(nil) // keep mcpserver import alive for future tool middlewares
}
`))

// buildDescription assembles the MCP tool description: explicit override if
// provided, else the proto leading comment. The MCP scope hint is appended
// in parentheses on its own line so the LLM client treats it as a usage note.
func buildDescription(m *parser.Method) string {
	desc := m.MCPDescription
	if desc == "" {
		desc = m.LeadingComment
	}
	if m.MCPScope != "" {
		if desc != "" {
			desc += "\n"
		}
		desc += "Available in: " + m.MCPScope
	}
	if desc == "" {
		desc = m.Name
	}
	return desc
}

// protoTypeRef mirrors the equivalent helper in internal/generator: returns
// the qualified Go type for a proto message, special-casing
// google.protobuf.Empty so the handler imports emptypb instead of pb.
func protoTypeRef(mt *parser.MessageType) string {
	if mt == nil {
		return "pb.Unknown"
	}
	if mt.FullName == ".google.protobuf.Empty" || mt.FullName == "google.protobuf.Empty" {
		return "emptypb.Empty"
	}
	return "pb." + mt.Name
}

func anyEmpty(svc *parser.Service) bool {
	for _, m := range svc.Methods {
		if !m.MCP {
			continue
		}
		if isEmpty(m.InputType) || isEmpty(m.OutputType) {
			return true
		}
	}
	return false
}

func isEmpty(mt *parser.MessageType) bool {
	if mt == nil {
		return false
	}
	return mt.FullName == ".google.protobuf.Empty" || mt.FullName == "google.protobuf.Empty"
}

// toSnakeCase converts CamelCase method names into snake_case tool names per
// the MCP convention: GetOpenTasks → get_open_tasks.
func toSnakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'A' && r <= 'Z' {
			b.WriteRune(r + 32)
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func protoImportPath(svc *parser.Service) string {
	if svc.GoPackage != "" {
		return svc.GoPackage
	}
	return strings.ReplaceAll(svc.ProtoPackage, ".", "/")
}
