package mcpgen

import (
	"fmt"
	"strings"
	"text/template"

	"github.com/mrs1lentcz/protobridge/internal/generator"
	"github.com/mrs1lentcz/protobridge/internal/parser"
)

// generateMain renders the MCP proxy entry point. It connects to the gRPC
// backend, builds an mcp.Server, registers every MCP-enabled service via
// the generated handler subpackage, then runs the server on the transport
// chosen via env.
func generateMain(api *parser.ParsedAPI, handlerPkg string, forwardKeys []string) (string, error) {
	data := mainData{
		HandlerPkg:  handlerPkg,
		ForwardKeys: forwardKeys,
	}
	for _, svc := range api.Services {
		if !serviceHasMCP(svc) {
			continue
		}
		screaming := toScreamingSnake(svc.Name)
		data.Services = append(data.Services, mainServiceData{
			ServiceName:    svc.Name,
			EnvAddr:        toLowerCamel(svc.Name) + "Addr",
			EnvAddrKey:     "PROTOBRIDGE_" + screaming + "_ADDR",
			EnvTLSKey:      "PROTOBRIDGE_" + screaming + "_TLS",
			EnvGRPCOptsKey: "PROTOBRIDGE_" + screaming + "_GRPC_OPTIONS",
		})
	}

	if len(data.Services) == 0 {
		return "", fmt.Errorf("no methods marked with (protobridge.mcp) = true; nothing to generate")
	}

	return generator.RenderTemplate(mainTmpl, data), nil
}

type mainData struct {
	HandlerPkg  string
	ForwardKeys []string // identity keys for DefaultAuthFunc (e.g. ["session_id"])
	Services    []mainServiceData
}

type mainServiceData struct {
	ServiceName    string
	EnvAddr        string
	EnvAddrKey     string
	EnvTLSKey      string
	EnvGRPCOptsKey string
}

var mainTmpl = template.Must(template.New("mcp_main").Parse(`// Code generated by protoc-gen-mcp. DO NOT EDIT.

package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/mrs1lentcz/gox/grpcx"
	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/credentials/insecure"

	"github.com/mrs1lentcz/protobridge/runtime"
	"github.com/mrs1lentcz/protobridge/runtime/mcp"
	"{{ .HandlerPkg }}"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	{{ range .Services -}}
	{{ .EnvAddr }} := runtime.PreferIPFamily(requireEnv("{{ .EnvAddrKey }}"))
	{{ end }}

	pool := grpcx.NewPool()
	pool.EnableHealthWatch(30 * time.Second)
	defer pool.Close()

	scalingCfg := grpcx.ScalingConfig{
		StreamsPerConn: 100,
		MaxConns:       10,
	}

	{{ range .Services }}
	if _, err := pool.ConnectScaled({{ .EnvAddr }}, scalingCfg, dialOpts("{{ .EnvTLSKey }}", "{{ .EnvGRPCOptsKey }}")...); err != nil {
		log.Fatalf("connect %s: %v", "{{ .ServiceName }}", err)
	}
	{{ end }}

	auth := mcp.DefaultAuthFunc({{ range $i, $k := .ForwardKeys }}{{ if $i }}, {{ end }}{{ printf "%q" $k }}{{ end }})
	srv := mcp.NewServer("protobridge-mcp", "0.0.0", auth)

	{{ range .Services -}}
	handler.Add{{ .ServiceName }}ToServer(srv, {{ .EnvAddr }}, pool, scalingCfg)
	{{ end }}

	if err := srv.ServeFromEnv(ctx); err != nil {
		log.Fatalf("serve: %v", err)
	}
}

func requireEnv(key string) string {
	v := os.Getenv(key)
	if v == "" {
		log.Fatalf("required env var %s is not set", key)
	}
	return v
}

func dialOpts(tlsEnvKey, grpcOptsEnvKey string) []grpc.DialOption {
	opts := []grpc.DialOption{
		grpc.WithStatsHandler(otelgrpc.NewClientHandler()),
	}
	if os.Getenv(tlsEnvKey) == "true" {
		opts = append(opts, grpc.WithTransportCredentials(credentials.NewTLS(nil)))
	} else {
		opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
	}

	if globalOpts := os.Getenv("PROTOBRIDGE_GRPC_OPTIONS"); globalOpts != "" {
		parsed, err := runtime.ParseGRPCOptions(globalOpts)
		if err != nil {
			log.Fatalf("PROTOBRIDGE_GRPC_OPTIONS: %v", err)
		}
		opts = append(opts, parsed...)
	}

	if serviceOpts := os.Getenv(grpcOptsEnvKey); serviceOpts != "" {
		parsed, err := runtime.ParseGRPCOptions(serviceOpts)
		if err != nil {
			log.Fatalf("%s: %v", grpcOptsEnvKey, err)
		}
		opts = append(opts, parsed...)
	}

	return opts
}
`))

func serviceHasMCP(svc *parser.Service) bool {
	for _, m := range svc.Methods {
		if m.MCP && m.StreamType == parser.StreamUnary {
			return true
		}
	}
	return false
}

func toScreamingSnake(s string) string {
	return strings.ToUpper(generator.ToSnakeCase(s))
}

func toLowerCamel(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'A' && r[0] <= 'Z' {
		r[0] += 32
	}
	return string(r)
}
