package mcpgen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"

	"github.com/mrs1lentcz/protobridge/internal/parser"
)

// generateMain renders the MCP proxy entry point. It connects to the gRPC
// backend, builds an mcp.Server, registers every MCP-enabled service via
// the generated handler subpackage, then runs the server on the transport
// chosen via env.
func generateMain(api *parser.ParsedAPI, handlerPkg string, forwardKeys []string) (string, error) {
	data := mainData{
		HandlerPkg:  handlerPkg,
		ForwardKeys: forwardKeys,
	}
	for _, svc := range api.Services {
		if !serviceHasMCP(svc) {
			continue
		}
		screaming := toScreamingSnake(svc.Name)
		data.Services = append(data.Services, mainServiceData{
			ServiceName:    svc.Name,
			EnvAddr:        toLowerCamel(svc.Name) + "Addr",
			EnvAddrKey:     "PROTOBRIDGE_" + screaming + "_ADDR",
			EnvTLSKey:      "PROTOBRIDGE_" + screaming + "_TLS",
			EnvGRPCOptsKey: "PROTOBRIDGE_" + screaming + "_GRPC_OPTIONS",
		})
	}

	if len(data.Services) == 0 {
		return "", fmt.Errorf("no methods marked with (protobridge.mcp) = true; nothing to generate")
	}

	var buf bytes.Buffer
	if err := mainTmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("gofmt mcp main: %w\n%s", err, buf.String())
	}
	return string(formatted), nil
}

type mainData struct {
	HandlerPkg  string
	ForwardKeys []string // identity keys for DefaultAuthFunc (e.g. ["session_id"])
	Services    []mainServiceData
}

type mainServiceData struct {
	ServiceName    string
	EnvAddr        string
	EnvAddrKey     string
	EnvTLSKey      string
	EnvGRPCOptsKey string
}

var mainTmpl = template.Must(template.New("mcp_main").Parse(`// Code generated by protoc-gen-mcp. DO NOT EDIT.

package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/mrs1lentcz/gox/grpcx"

	"github.com/mrs1lentcz/protobridge/runtime/mcp"
	"{{ .HandlerPkg }}"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	{{ range .Services -}}
	{{ .EnvAddr }} := requireEnv("{{ .EnvAddrKey }}")
	{{ end }}

	pool := grpcx.NewPool()
	pool.EnableHealthWatch(30 * 1_000_000_000) // 30s, expressed in ns to avoid time import
	defer pool.Close()

	scalingCfg := grpcx.ScalingConfig{
		StreamsPerConn: 100,
		MaxConns:       10,
	}

	{{ range .Services }}
	if _, err := pool.ConnectScaled({{ .EnvAddr }}, scalingCfg); err != nil {
		log.Fatalf("connect %s: %v", "{{ .ServiceName }}", err)
	}
	{{ end }}

	auth := mcp.DefaultAuthFunc({{ range $i, $k := .ForwardKeys }}{{ if $i }}, {{ end }}{{ printf "%q" $k }}{{ end }})
	srv := mcp.NewServer("protobridge-mcp", "0.0.0", auth)

	{{ range .Services -}}
	handler.Add{{ .ServiceName }}ToServer(srv, {{ .EnvAddr }}, pool, scalingCfg)
	{{ end }}

	if err := srv.ServeFromEnv(ctx); err != nil {
		log.Fatalf("serve: %v", err)
	}
}

func requireEnv(key string) string {
	v := os.Getenv(key)
	if v == "" {
		log.Fatalf("required env var %s is not set", key)
	}
	return v
}
`))

func serviceHasMCP(svc *parser.Service) bool {
	for _, m := range svc.Methods {
		if m.MCP && m.StreamType == parser.StreamUnary {
			return true
		}
	}
	return false
}

func toScreamingSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'a' && r <= 'z' {
			b.WriteRune(r - 32)
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func toLowerCamel(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'A' && r[0] <= 'Z' {
		r[0] += 32
	}
	return string(r)
}
