package mcpgen

import (
	"encoding/json"
	"sort"

	"github.com/mrs1lentcz/protobridge/internal/parser"
)

// generateOpenRPC renders an OpenRPC 1.3.2 document describing every
// MCP-enabled unary method across api.Services. OpenRPC is the JSON-RPC
// equivalent of OpenAPI — clients can run openrpc-generator against this
// document to scaffold typed wrappers (Go, TypeScript, Python, ...) for
// every tool, instead of hand-rolling JSON-RPC envelopes.
//
// MCP's wire protocol is technically `tools/call` with `{name, arguments}`,
// but for codegen UX each tool is exposed as its own OpenRPC method;
// generated client libraries usually hide the `tools/call` wrapping at
// runtime. Top-level fields of the input message become named OpenRPC
// params so generated clients get one named arg per field.
func generateOpenRPC(api *parser.ParsedAPI) string {
	doc := openRPCDoc{
		OpenRPC: "1.3.2",
		Info: openRPCInfo{
			Title:       "MCP API",
			Version:     "0.0.0",
			Description: "Auto-generated by protoc-gen-mcp from proto annotations.",
		},
	}
	for _, svc := range api.Services {
		for _, m := range svc.Methods {
			if !m.MCP || m.StreamType != parser.StreamUnary {
				continue
			}
			doc.Methods = append(doc.Methods, openRPCMethod{
				Name:        toSnakeCase(m.Name),
				Summary:     summaryLine(m.LeadingComment),
				Description: buildDescription(m),
				Params:      paramsFromMessage(m.InputType),
				Result: openRPCContentDescriptor{
					Name:   "result",
					Schema: messageSchemaOrEmpty(m.OutputType),
				},
			})
		}
	}
	// Stable ordering: alphabetical by method name. Keeps generated client
	// diffs deterministic across regenerations.
	sort.Slice(doc.Methods, func(i, j int) bool {
		return doc.Methods[i].Name < doc.Methods[j].Name
	})
	out, _ := json.MarshalIndent(doc, "", "  ")
	return string(out)
}

// generateMCPTools renders the native MCP tools manifest — the same JSON
// shape a server returns from `tools/list`. Cached to disk so MCP clients
// (mcp-cli, mcp-inspector, py-mcp, ts-mcp, mark3labs/mcp-go) can introspect
// the tool surface without booting the proxy. Convention: wrapped in
// {"tools": [...]} so it can be served verbatim as a tools/list response.
func generateMCPTools(api *parser.ParsedAPI) string {
	doc := mcpToolsDoc{}
	for _, svc := range api.Services {
		for _, m := range svc.Methods {
			if !m.MCP || m.StreamType != parser.StreamUnary {
				continue
			}
			doc.Tools = append(doc.Tools, mcpTool{
				Name:        toSnakeCase(m.Name),
				Description: buildDescription(m),
				InputSchema: messageSchemaOrEmpty(m.InputType),
			})
		}
	}
	sort.Slice(doc.Tools, func(i, j int) bool {
		return doc.Tools[i].Name < doc.Tools[j].Name
	})
	out, _ := json.MarshalIndent(doc, "", "  ")
	return string(out)
}

// --- helpers ---

func paramsFromMessage(mt *parser.MessageType) []openRPCContentDescriptor {
	if mt == nil || len(mt.Fields) == 0 {
		return nil
	}
	out := make([]openRPCContentDescriptor, 0, len(mt.Fields))
	for _, f := range mt.Fields {
		if f.OneofIndex != nil {
			continue
		}
		out = append(out, openRPCContentDescriptor{
			Name:     f.Name,
			Schema:   fieldSchema(f, map[string]bool{}),
			Required: f.Required,
		})
	}
	return out
}

func messageSchemaOrEmpty(mt *parser.MessageType) map[string]any {
	if mt == nil || len(mt.Fields) == 0 {
		return map[string]any{"type": "object"}
	}
	return messageSchema(mt, map[string]bool{})
}

// summaryLine extracts the first line of a multi-line proto comment. Used
// for OpenRPC's `summary` field which is shown in API browsers / tooltips.
func summaryLine(comment string) string {
	for i := 0; i < len(comment); i++ {
		if comment[i] == '\n' {
			return comment[:i]
		}
	}
	return comment
}

// --- OpenRPC document types ---

type openRPCDoc struct {
	OpenRPC string          `json:"openrpc"`
	Info    openRPCInfo     `json:"info"`
	Methods []openRPCMethod `json:"methods"`
}

type openRPCInfo struct {
	Title       string `json:"title"`
	Version     string `json:"version"`
	Description string `json:"description,omitempty"`
}

type openRPCMethod struct {
	Name        string                     `json:"name"`
	Summary     string                     `json:"summary,omitempty"`
	Description string                     `json:"description,omitempty"`
	Params      []openRPCContentDescriptor `json:"params"`
	Result      openRPCContentDescriptor   `json:"result"`
}

type openRPCContentDescriptor struct {
	Name     string         `json:"name"`
	Schema   map[string]any `json:"schema"`
	Required bool           `json:"required,omitempty"`
}

// --- MCP tools manifest types (matches mcp.Tool / ListToolsResult shape) ---

type mcpToolsDoc struct {
	Tools []mcpTool `json:"tools"`
}

type mcpTool struct {
	Name        string         `json:"name"`
	Description string         `json:"description,omitempty"`
	InputSchema map[string]any `json:"inputSchema"`
}
